export const betaAgreement = `

Unlimited - Meditation Player Beta Terms of Use

In order to participate in the Unlimited - Meditation Player Beta Program you must agree to these Unlimited Beta Terms of Use (the “Agreement”).

Unlimited - Meditation Player ("Unlimited") has designed and developed a Unlimited Beta Program ("Unlimited Beta Program") to, among other things, allow a limited number of people to download test versions of Unlimited application for mobile devices (the “Experimental Software”), such as Unlimited for Android or Unlimited for iOS applications, and to provide feedback and comments to Unlimited regarding use of such applications. By joining the Unlimited Beta Program, you agree to be bound by the terms and conditions set forth below (the "Agreement").

1. Your Feedback By enrolling in the Unlimited Beta Program you will have the ability to: (a) download, test, evaluate and analyze the Experimental Software (b) and provide feedback, analysis, suggestions and comments to Unlimited (including, but not limited to, bug reports and test results) (collectively, “Feedback”).

By participating in the Unlimited Beta Program, you agree that any Feedback you provide will become the property of Unlimited and you agree that Unlimited may use or otherwise exploit all or part of your feedback or any derivative thereof in any manner or media now known without any further remuneration, compensation or credit to you. You represent and warrant that you have right to enter into this Agreement and assign and grant the rights set forth herein, and that any Feedback which is provided by you hereunder is original work made solely by you and does not infringe any third party intellectual property rights.

2. Confidentiality Confidential Information. The Unlimited Beta Program is designed to assist Unlimited in researching, analyzing and validating the usability and reliability of certain prospective product features (collectively, the “Purpose”). Unlimited may disclose to you certain information (tangible or intangible) that you agree to treat as Confidential Information as set forth below. Definition. “Confidential Information” means all information disclosed by Unlimited, including, without limitation, documents, designs, techniques, specifications, product plans, strategic information, existing or prospective business plans, existing or prospective product study or pilot test objectives and/or results, and other information related to the Purpose. Consistent with the foregoing, Unlimited may also disclose Confidential Information related to certain unreleased and experimental product features or plans.

Obligations Regarding Confidential Information. You agree to: (a) use Confidential Information only for the Purpose; (b) not disclose Confidential Information to any third parties (including the sharing of unreleased/experimental product images); and (c) use the same degree of care, but no less than a reasonable degree of care (including reasonable security measures), to prevent the unauthorized use, dissemination or publication of Confidential Information as you would use to protect your own confidential information of like nature.

Remedies. You agree that any breach of this Agreement by you may result in irreparable harm to Unlimited, for which damages would be an inadequate remedy and therefore, in addition to its rights and remedies otherwise available at law, Unlimited shall be entitled to seek equitable relief, including injunction, in the event of such breach.

3. No Compensation or Employment. You acknowledge that you are participating in the Unlimited Beta Program on a purely voluntary basis, as a means of assisting, and in consideration of the opportunity to assist Unlimited to use, implement, and understand various facets of the Experimental Software. Unlimited, at its sole discretion, may provide you compensation for your participation and/or Feedback but you acknowledge and agree that Unlimited has no obligation to do so. Unlimited makes no guarantee or representation as to whether or not your Feedback regarding the Experimental Software will be used, and you understand and acknowledge that Unlimited will not compensate you for your participation in the Unlimited Beta Program. Furthermore, you acknowledge and agree that nothing in this Agreement or in your voluntary submission of Feedback creates any employment relationship between you and Unlimited.

4. Unlimited may, in its sole discretion, at any time, terminate or discontinue the Unlimited Beta Program, discontinue your participation in the Unlimited Beta Program, or remove your Feedback. You acknowledge and agree that all such decisions by Unlimited are final and Unlimited will have no liability with respect to such decisions.

5. No Warranty from UNLIMITED YOU EXPRESSLY AGREE THAT YOUR PARTICIPATION IN THE UNLIMITED BETA PROGRAM IS AT YOUR OWN RISK. THE UNLIMITED BETA PROGRAM IS AVAILABLE ON AN "AS IS" BASIS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. UNLIMITED EXPRESSLY DISCLAIMS ON ITS OWN BEHALF AND ON BEHALF OF ITS EMPLOYEES, AGENTS, ATTORNEYS, CONSULTANTS, OR CONTRACTORS ANY AND ALL WARRANTIES INCLUDING, WITHOUT LIMITATION (i) ANY WARRANTY OR REPRESENTATION WHATSOEVER REGARDING THE OPERATION OF THE UNLIMITED BETA PROGRAM, THE AVAILABILITY, ACCURACY OR CONTENT OF ANY INFORMATION, SERVICES, OR PRODUCTS PROVIDED OR AVAILABLE THROUGH OR IN CONNECTION WITH THE UNLIMITED BETA PROGRAM, THE EXPERIMENTAL SOFTWARE, UNLIMITED, AND/OR THE UNLIMITED WEB SITE OR ANY RESULTS OBTAINED THROUGH THE USE THEREOF, AND (ii) THE WARRANTIES OR CONDITIONS OF NONINFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR ANY PARTICULAR PURPOSE. SOME STATES DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS, WHICH VARY FROM STATE TO STATE.

7. Limitations of Liability IN NO EVENT SHALL UNLIMITED, ITS EMPLOYEES, AGENTS, ATTORNEYS, CONSULTANTS, OR CONTRACTORS BE LIABLE UNDER THIS AGREEMENT FOR ANY CONSEQUENTIAL, SPECIAL, LOST PROFITS, INDIRECT OR OTHER DAMAGES, INCLUDING BUT NOT LIMITED TO LOST PROFITS, LOSS OF BUSINESS, COST OF COVER WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, EVEN IF UNLIMITED HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. IN ANY EVENT, UNLIMITED’S, ITS EMPLOYEES’, AGENTS’, ATTORNEYS’, CONSULTANTS’ OR CONTRACTORS’ AGGREGATE LIABILITY UNDER THIS AGREEMENT FOR ANY CLAIM SHALL BE STRICTLY LIMITED TO $100.00. SOME STATES DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. You acknowledge that UNLIMITED has entered into this Agreement in reliance upon the limitations of liability set forth herein and that the same is an essential basis of the bargain between the parties.

8. Entire Agreement These Terms, the Unlimited Terms of Service and Privacy Policy are the entire and exclusive agreement of the parties regarding the subject matter of this Agreement and supersedes all previous communications, representations, understandings and agreements, either oral or written, between you and Unlimited. Unlimited may modify the terms of this Agreement at any time upon notice published on the Unlimited website. Your continued participation in the Unlimited Beta Program after such notice shall be deemed to be continued acceptance of this Agreement including its amendments and modifications.

9. The Recipient’s obligations under this Agreement shall survive any termination of this agreement. This Agreement shall be governed by and construed in accordance with the laws of California. The Recipient hereby agrees that breach of this Agreement will cause Company irreparable damage for which recovery of damages would be inadequate, and that the Company shall therefore be entitled to obtain timely injunctive relief under this Agreement, as well as such further relief as may be granted by a court of competent jurisdiction.  The Recipient will not assign or transfer any rights or obligations under this Agreement without the prior written consent of the Company.


`