import { MeditationBaseMap, MeditationMap, MeditationTypes } from "../types";

export enum MeditationBaseKeys {
  MedNewPotentialsV1 = 'm-new-potentials-v1',
  BreathNewPotentialsV1 = 'b-new-potentials-v1',
  MedBreakingHabitSpaceV1 = 'm-breaking-habit-space-v1',
  MedBreakingHabitWaterV1 = 'm-breaking-habit-water-v1',
  MedPresentMomentV1 = 'm-present-moment-v1',
  MedDailyMorningV1 = 'm-daily-morning-v1',
  MedDailyEveningV1 = 'm-daily-evening-v1',
  MedReconditionV1 = 'm-recondition-v1',
  BreathReconditionV1 = 'b-recondition-v1',
  MedBlessingCenter1V1 = 'm-blessing-center-1-v1',
  MedBlessingCenter2V1 = 'm-blessing-center-2-v1',
  MedBlessingCenter3V1 = 'm-blessing-center-3-v1',
  MedBlessingCenter4V1 = 'm-blessing-center-4-v1',
  MedBlessingCenter5V1 = 'm-blessing-center-5-v1',
  MedBlessingCenter6V1 = 'm-blessing-center-6-v1',
  MedBlessingCenter7V1 = 'm-blessing-center-7-v1',
  MedBlessingCenter8V1 = 'm-blessing-center-8-v1',
  MedBlessingCenter9V1 = 'm-blessing-center-9-v1',
}

export enum MeditationStringSizes {
  MedNewPotentialsV1 = '56004',
  BreathNewPotentialsV1 = '96748',
  MedBreakingHabitSpaceV1 = '14936',
  MedBreakingHabitWaterV1 = '14071',
  MedPresentMoment = '68710',
  MedRecondition = '55295',
  BreathRecondition = '95032',
  MedBlessingCenter1V1 = '61719',
  MedBlessingCenter2V1 = '69705',
  MedBlessingCenter3V1 = '77717',
  MedBlessingCenter4V1 = '93864',
  MedBlessingCenter5V1 = '10421',
  MedBlessingCenter6V1 = '11010',
  MedBlessingCenter7V1 = '10765',
  MedBlessingCenter8V1 = '13596',
  MedBlessingCenter9V1 = '21175',
}

export enum MeditationKeys {
  NewPotentials = '56004113',
  NewPotentialsBreath = '9674897',
  BreakingTheHabit = '149360649',
  BreakingTheHabitWater = '140710975',
  PresentMoment = '68710984',
  Recondition = '55295394',
  ReconditionBreath = '9503256',
}

export enum MeditationSizes {
  NewPotentials = 56004113,
  NewPotentialsBreath = 9674897,
  BreakingTheHabit = 149360649,
  BreakingTheHabitWater = 140710975,
  PresentMoment = 68710984,
  Recondition = 55295394,
  ReconditionBreath = 9503256,
  BlessingEnergyCenter1V1 = 61719924,
  BlessingEnergyCenter2V1 = 69705557,
  BlessingEnergyCenter3V1 = 77717479,
  BlessingEnergyCenter4V1 = 93864414,
  BlessingEnergyCenter5V1 = 104215154,
  BlessingEnergyCenter6V1 = 110108828,
  BlessingEnergyCenter7V1 = 107656059,
  BlessingEnergyCenter8V1 = 135964319,
  BlessingEnergyCenter9V1 = 211753731,
}

export enum MeditationGroupKey {
  'EnergyCenter' = 'energyCenter',
  'NewPotential' = 'newPotential',
  'BreakingHabit' = 'breakingHabit',
  'Recondition' = 'recondition',
  'Other' = 'other',
}

export enum MeditationGroupName {
  'EnergyCenter' = 'Blessing of the Energy Centers',
  'NewPotential' = 'Tuning Into New Potentials',
  'BreakingHabit' = 'Breaking the Habit of Being Yourself',
  'Recondition' = 'Reconditioning the Body to a New Mind',
  'Other' = 'Other'
}

const artist = 'Dr. Joe Dispenza';
const placeholder = '';

export const meditationBaseMap: MeditationBaseMap = {
  [MeditationBaseKeys.MedNewPotentialsV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    color: '#055304',
    formattedDuration: '45',
    id: placeholder,
    groupKey: MeditationGroupKey.NewPotential,
    groupName: MeditationGroupName.NewPotential,
    meditationBaseId: MeditationBaseKeys.MedNewPotentialsV1,
    name: 'Tuning Into New Potentials',
    size: MeditationSizes.NewPotentials,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathNewPotentialsV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    color: '#055304',
    formattedDuration: '7',
    id: placeholder,
    groupKey: MeditationGroupKey.NewPotential,
    groupName: MeditationGroupName.NewPotential,
    meditationBaseId: MeditationBaseKeys.BreathNewPotentialsV1,
    name: 'Tuning Into New Potentials - Breath',
    size: MeditationSizes.NewPotentialsBreath,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBreakingHabitSpaceV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/breaking_habit.jpg'),
    color: '#003E54',
    formattedDuration: '15',
    id: placeholder,
    groupKey: MeditationGroupKey.BreakingHabit,
    groupName: MeditationGroupName.BreakingHabit,
    meditationBaseId: MeditationBaseKeys.MedBreakingHabitSpaceV1,
    name: 'Breaking The Habit Of Being Yourself',
    size: MeditationSizes.BreakingTheHabit,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBreakingHabitWaterV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/breaking_habit.jpg'),
    color: '#003E54',
    formattedDuration: '11',
    id: placeholder,
    groupKey: MeditationGroupKey.BreakingHabit,
    groupName: MeditationGroupName.BreakingHabit,
    meditationBaseId: MeditationBaseKeys.MedBreakingHabitWaterV1,
    name: 'Breaking The Habit Of Being Yourself - Water',
    size: MeditationSizes.BreakingTheHabitWater,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedPresentMomentV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/present_moment.jpg'),
    color: '#003E54',
    formattedDuration: '47',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedPresentMomentV1,
    name: 'Generous Present Moment',
    size: MeditationSizes.PresentMoment,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedReconditionV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/recondition.jpg'),
    color: '#003E54',
    formattedDuration: '46',
    id: placeholder,
    groupKey: MeditationGroupKey.Recondition,
    groupName: MeditationGroupName.Recondition,
    meditationBaseId: MeditationBaseKeys.MedReconditionV1,
    name: 'Reconditioning the Body to a New Mind',
    size: MeditationSizes.Recondition,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathReconditionV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/recondition.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.Recondition,
    groupName: MeditationGroupName.Recondition,
    meditationBaseId: MeditationBaseKeys.BreathReconditionV1,
    name: 'Reconditioning the Body to a New Mind - Breath',
    size: MeditationSizes.ReconditionBreath,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter1V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-1.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter1V1,
    name: 'Blessing of the Energy Centers 1',
    size: MeditationSizes.BlessingEnergyCenter1V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter2V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-2.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter2V1,
    name: 'Blessing of the Energy Centers 2',
    size: MeditationSizes.BlessingEnergyCenter2V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter3V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-3.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter3V1,
    name: 'Blessing of the Energy Centers 3',
    size: MeditationSizes.BlessingEnergyCenter3V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter4V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-4.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter4V1,
    name: 'Blessing of the Energy Centers 4',
    size: MeditationSizes.BlessingEnergyCenter4V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter5V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-5.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter5V1,
    name: 'Blessing of the Energy Centers 5',
    size: MeditationSizes.BlessingEnergyCenter5V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter6V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-6.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter6V1,
    name: 'Blessing of the Energy Centers 6',
    size: MeditationSizes.BlessingEnergyCenter6V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter7V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-7.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter7V1,
    name: 'Blessing of the Energy Centers 7',
    size: MeditationSizes.BlessingEnergyCenter7V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter8V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-8.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter8V1,
    name: 'Blessing of the Energy Centers 8',
    size: MeditationSizes.BlessingEnergyCenter8V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter9V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-9.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.EnergyCenter,
    groupName: MeditationGroupName.EnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter9V1,
    name: 'Blessing of the Energy Centers 9',
    size: MeditationSizes.BlessingEnergyCenter9V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
}

export const newPotentialGroupIds = [MeditationKeys.NewPotentials, MeditationKeys.NewPotentialsBreath]
export const breakingHabitGroupIds = [MeditationKeys.BreakingTheHabit, MeditationKeys.BreakingTheHabitWater];

export const breathMeditationTypeBaseIds = [
  MeditationBaseKeys.BreathNewPotentialsV1,
  MeditationBaseKeys.BreathReconditionV1,
]
