import {MeditationBaseMap, MeditationTypes} from '../types';

const artist = 'Dr. Joe Dispenza';
const placeholder = '';

export enum MeditationGroupName {
  'BlessingEnergyCenter' = 'Blessing of the Energy Centers',
  'BreakingHabit' = 'Breaking the Habit of Being Yourself',
  'BreathTracks' = 'Breathwork',
  'Custom' = 'Custom',
  'Daily' = 'Daily Meditations',
  'Foundational' = 'Foundational - Progressive',
  'Generating' = 'Generating Series',
  'Other' = 'Other',
  'Synchronize' = 'Synchronize Series',
  'Walking' = 'Walking',
  'Unlocked' = 'Unlocked Series',
}

/* Blessing Energy Centers */

export enum BotecBaseKeys {
  MedBotec1 = 'm-botec-1',
  MedBotec1Updated = 'm-botec-1-updated',
  MedBotec2 = 'm-botec-2',
  MedBotec2Updated = 'm-botec-2-updated',
  MedBotec3 = 'm-botec-3',
  MedBotec3Updated = 'm-botec-3-updated',
  MedBotec4 = 'm-botec-4',
  MedBotec5 = 'm-botec-5',
  MedBotec6 = 'm-botec-6',
  MedBotec7 = 'm-botec-7',
  MedBotec8 = 'm-botec-8',
  MedBotec9 = 'm-botec-9',
  MedBotec10 = 'm-botec-10',
}

export enum BotecSizes {
  MedBotec1 = 61719924,
  MedBotec1Updated = 46805906,
  MedBotec1Updated2 = 69591725,
  MedBotec2 = 69705557,
  MedBotec2Updated = 48109982,
  MedBotec2Updated3 = 71520658,
  MedBotec3 = 77717479,
  MedBotec3Updated = 52464670,
  MedBotec4 = 93864414,
  MedBotec4s2 = 63072459,
  MedBotec5 = 104215154,
  MedBotec5s2 = 68575709,
  MedBotec6 = 110108828,
  MedBotec6s2 = 73078110,
  MedBotec7 = 107656059,
  MedBotec7s2 = 72338676,
  MedBotec8 = 135964319,
  MedBotec8s2 = 91332341,
  MedBotec9 = 211753731,
  MedBotec9s2 = 149230439,
  MedBotec9s3 = 85552981,
  MedBotec10 = 138202744,
  MedBotec10s2 = 55797552,
}

export enum BotecStringSizes {
  MedBotec1 = '61719',
  MedBotec1Updated = '46805',
  MedBotec1Updated2 = '69591',
  MedBotec2 = '69705',
  MedBotec2Updated = '48109',
  MedBotec2Updated3 = '71520',
  MedBotec3 = '77717',
  MedBotec3Updated = '52464',
  MedBotec4 = '93864',
  MedBotec4s2 = '63072',
  MedBotec5 = '10421',
  MedBotec5s2 = '68575',
  MedBotec6 = '11010',
  MedBotec6s2 = '73078',
  MedBotec6s3 = '93829',
  MedBotec7 = '10765',
  MedBotec7s2 = '72338',
  MedBotec8 = '13596',
  MedBotec8s2 = '91332',
  MedBotec9 = '21175',
  MedBotec9s2 = '14923',
  MedBotec9s3 = '85552',
  MedBotec10 = '13820',
  MedBotec10s2 = '55797',
}

export const botecMap = {
  [BotecBaseKeys.MedBotec1]: {
    artist,
    backgroundImage: require('../assets/bec-1.jpg'),
    formattedDuration: '42',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec1,
    name: 'Blessing of the Energy Centers 01',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec1Updated]: {
    artist,
    backgroundImage: require('../assets/bec-1.jpg'),
    formattedDuration: '48',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec1Updated,
    name: 'Blessing of the Energy Centers 01 - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec2]: {
    artist,
    backgroundImage: require('../assets/bec-2.jpg'),
    formattedDuration: '47',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec2,
    name: 'Blessing of the Energy Centers 02',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec2Updated]: {
    artist,
    backgroundImage: require('../assets/bec-2.jpg'),
    formattedDuration: '49',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec2Updated,
    name: 'Blessing of the Energy Centers 02 - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec3]: {
    artist,
    backgroundImage: require('../assets/bec-3.jpg'),
    formattedDuration: '54',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec3,
    name: 'Blessing of the Energy Centers 03',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec3Updated]: {
    artist,
    backgroundImage: require('../assets/bec-3.jpg'),
    formattedDuration: '54',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec3Updated,
    name: 'Blessing of the Energy Centers 03 - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec4]: {
    artist,
    backgroundImage: require('../assets/bec-4.jpg'),
    formattedDuration: '65',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec4,
    name: 'Blessing of the Energy Centers 04',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec5]: {
    artist,
    backgroundImage: require('../assets/bec-5.jpg'),
    formattedDuration: '71',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec5,
    name: 'Blessing of the Energy Centers 05',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec6]: {
    artist,
    backgroundImage: require('../assets/bec-6.jpg'),
    formattedDuration: '75',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec6,
    name: 'Blessing of the Energy Centers 06',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec7]: {
    artist,
    backgroundImage: require('../assets/bec-7.jpg'),
    formattedDuration: '74',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec7,
    name: 'Blessing of the Energy Centers 07',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec8]: {
    artist,
    backgroundImage: require('../assets/bec-8.jpg'),
    formattedDuration: '94',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec8,
    name: 'Blessing of the Energy Centers 08',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec9]: {
    artist,
    backgroundImage: require('../assets/bec-9.jpg'),
    formattedDuration: '88',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec9,
    name: 'Blessing of the Energy Centers 09',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BotecBaseKeys.MedBotec10]: {
    artist,
    backgroundImage: require('../assets/bec-10.jpg'),
    formattedDuration: '62',
    id: placeholder,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: BotecBaseKeys.MedBotec10,
    name: 'Blessing of the Energy Centers 10',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Breaking The Habit */

export enum BreakingHabitBaseKeys {
  MedBreakingHabitSpace = 'm-breaking-habit-space',
  MedBreakingHabitWater = 'm-breaking-habit-water',
  MedBreakingHabitPlacebo = 'm-breaking-habit-placebo',
}

export enum BreakingHabitSizes {
  MedBreakingHabitSpace = 149360649,
  MedBreakingHabitWater = 140710975,
  MedBreakingHabitPlacebo = 58249006,
}

export enum BreakingHabitStringSizes {
  MedBreakingHabitSpace = '149360649',
  MedBreakingHabitWater = '140710975',
  MedBreakingHabitPlacebo = '58249',
}

export const breakingHabitMap = {
  [BreakingHabitBaseKeys.MedBreakingHabitSpace]: {
    artist,
    backgroundImage: require('../assets/breaking_habit.jpg'),
    formattedDuration: '74',
    id: placeholder,
    groupName: MeditationGroupName.BreakingHabit,
    meditationBaseId: BreakingHabitBaseKeys.MedBreakingHabitSpace,
    name: 'Breaking The Habit Of Being Yourself',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BreakingHabitBaseKeys.MedBreakingHabitWater]: {
    artist,
    backgroundImage: require('../assets/breaking_habit.jpg'),
    formattedDuration: '70',
    id: placeholder,
    groupName: MeditationGroupName.BreakingHabit,
    meditationBaseId: BreakingHabitBaseKeys.MedBreakingHabitWater,
    name: 'Breaking The Habit Of Being Yourself - Water',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [BreakingHabitBaseKeys.MedBreakingHabitPlacebo]: {
    artist,
    backgroundImage: require('../assets/placebo.jpg'),
    formattedDuration: '69',
    id: placeholder,
    groupName: MeditationGroupName.BreakingHabit,
    meditationBaseId: BreakingHabitBaseKeys.MedBreakingHabitPlacebo,
    name: 'You are the Placebo',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Daily Meditations */

export enum DailyMeditationBaseKeys {
  MedMorning = 'm-morning',
  MedMorningUpdated = 'm-morning-updated',
  MedEvening = 'm-evening',
  MedEveningUpdated = 'm-evening-updated',
}

export enum DailyMeditationSizes {
  MedMorning = 34907925,
  MedMorning2 = 23187022,
  MedMorningUpdated = 33578871,
  MedMorningUpdated2 = 57534699,
  MedEvening = 34099801,
  MedEvening2 = 29178857,
  MedEveningUpdated = 29178857,
  MedEveningUpdated2 = 56234919,
  MedEveningUpdated3 = 88207387,
  MedEveningUpdated4 = 77225548,
}

export enum DailyMeditationStringSizes {
  MedMorning = '34907925',
  MedMorning2 = '23187',
  MedMorningUpdated = '33578',
  MedMorningUpdated2 = '57534',
  MedEvening = '34099',
  MedEvening2 = '22604',
  MedEveningUpdated = '29178',
  MedEveningUpdated2 = '56234',
  MedEveningUpdated3 = '88207',
  MedEveningUpdated4 = '77225',
}

export const dailyMeditationsMap = {
  [DailyMeditationBaseKeys.MedMorning]: {
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    formattedDuration: '24',
    id: placeholder,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: DailyMeditationBaseKeys.MedMorning,
    name: 'Daily Morning',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [DailyMeditationBaseKeys.MedMorningUpdated]: {
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    formattedDuration: '24',
    id: placeholder,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: DailyMeditationBaseKeys.MedMorningUpdated,
    name: 'Daily Morning - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [DailyMeditationBaseKeys.MedEvening]: {
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    formattedDuration: '24',
    id: placeholder,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: DailyMeditationBaseKeys.MedEvening,
    name: 'Daily Evening',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [DailyMeditationBaseKeys.MedEveningUpdated]: {
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    formattedDuration: '23',
    id: placeholder,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: DailyMeditationBaseKeys.MedEveningUpdated,
    name: 'Daily Evening - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Generating Series */
export enum GeneratingBaseKeys {
  MedGeneratingAbundance = 'm-generating-abundance',
  MedGeneratingFlow = 'm-generating-flow',
  MedGeneratingGratitude = 'm-generating-gratitude',
  MedGeneratingEmpowerment = 'm-generating-empowerment',
  MedGeneratingChange = 'm-generating-change',
  MedGeneratingInspiration = 'm-generating-inspiration',
  MedGeneratingJoy = 'm-generating-joy',
}

export enum GeneratingSizes {
  MedGeneratingAbundance = 86671093,
  MedGeneratingAbundance2 = 58213320,
  MedGeneratingFlow = 14599092,
  MedGeneratingFlow2 = 36484250,
  MedGeneratingGratitude = 14594274,
  MedGeneratingGratitude2 = 36493475,
  MedGeneratingGratitude3 = 27173877,
  MedGeneratingEmpowerment = 14596134,
  MedGeneratingEmpowerment2 = 14578838,
  MedGeneratingEmpowerment3 = 36498782,
  MedGeneratingChange = 14599015,
  MedGeneratingChange2 = 36503450,
  MedGeneratingInspiration = 15099669,
  MedGeneratingInspiration2 = 37713033,
  MedGeneratingJoy = 14593178,
  MedGeneratingJoy2 = 36479295,
}

export enum GeneratingStringSizes {
  MedGeneratingAbundance = '86671',
  MedGeneratingAbundance2 = '58213',
  MedGeneratingFlow = '14599',
  MedGeneratingFlow2 = '36484',
  MedGeneratingGratitude = '14594',
  MedGeneratingGratitude2 = '36493',
  MedGeneratingGratitude3 = '27173',
  MedGeneratingEmpowerment = '14596',
  MedGeneratingEmpowerment2 = '14578',
  MedGeneratingEmpowerment3 = '36498',
  MedGeneratingChange = '14599',
  MedGeneratingChange2 = '36503',
  MedGeneratingInspiration = '15099',
  MedGeneratingInspiration2 = '37713',
  MedGeneratingJoy = '14593',
  MedGeneratingJoy2 = '36479',
}

export const generatingMap = {
  [GeneratingBaseKeys.MedGeneratingAbundance]: {
    artist,
    backgroundImage: require('../assets/abundance.jpg'),
    formattedDuration: '60',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: GeneratingBaseKeys.MedGeneratingAbundance,
    name: 'Generating Abundance',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [GeneratingBaseKeys.MedGeneratingFlow]: {
    artist,
    backgroundImage: require('../assets/flow.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: GeneratingBaseKeys.MedGeneratingFlow,
    name: 'Generating Flow',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [GeneratingBaseKeys.MedGeneratingGratitude]: {
    artist,
    backgroundImage: require('../assets/gratitude.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: GeneratingBaseKeys.MedGeneratingGratitude,
    name: 'Generating Gratitude',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [GeneratingBaseKeys.MedGeneratingEmpowerment]: {
    artist,
    backgroundImage: require('../assets/empowerment.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: GeneratingBaseKeys.MedGeneratingEmpowerment,
    name: 'Generating Empowerment',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [GeneratingBaseKeys.MedGeneratingChange]: {
    artist,
    backgroundImage: require('../assets/change.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: GeneratingBaseKeys.MedGeneratingChange,
    name: 'Generating Change',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [GeneratingBaseKeys.MedGeneratingInspiration]: {
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: GeneratingBaseKeys.MedGeneratingInspiration,
    name: 'Generating Inspiration',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [GeneratingBaseKeys.MedGeneratingJoy]: {
    artist,
    backgroundImage: require('../assets/generate-joy.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: GeneratingBaseKeys.MedGeneratingJoy,
    name: 'Generating Joy',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Breath Work Tacks */

export enum BreathBaseKeys {
  BreathNewPotentials = 'b-new-potentials',
  BreathNewPotentialsUpdated = 'b-new-potentials-updated',
  BreathReconditioning = 'b-reconditioning',
  BreathChangingBeliefsAndPerceptions = 'b-changing-beliefs-and-perceptions',
  BreathInspireTribalTrance = 'b-inspire-tribal-trance',
  BreathInspireEmergingHeart = 'b-inspire-emerging-heart',
  BreathInspireSuenosSelva = 'b-inspire-suenos-selva',
  BreathInspireInferno = 'b-inspire-inferno',
  BreathInspireRefuge = 'b-inspire-refuge',
  BreathInspireKingFisher = 'b-inspire-king-fisher',
  BreathInspireShamanGoddess = 'b-inspire-shaman-goddess',
  BreathInspireCleansing = 'b-inspire-cleansing',
  BreathInspireAspiration = 'b-inspire-aspiration',
  BreathInspireBreathingLife = 'b-inspire-breathing-life',
}

export enum BreathSizes {
  BreathNewPotentials = 9674897,
  BreathNewPotentialsUpdated = 17014748,
  BreathReconditioning = 9503256,
  BreathChangingBeliefsAndPerceptions = 18036880,
  BreathChangingBeliefsAndPerceptions2 = 11743205,
  BreathInspireTribalTrance = 12921155,
  BreathInspireEmergingHeart = 20626928,
  BreathInspireSuenosSelva = 12733215,
  BreathInspireInferno = 12909654,
  BreathInspireRefuge = 18921020,
  BreathInspireKingFisher = 17862421,
  BreathInspireShamanGoddess = 11812429,
  BreathInspireCleansing = 18238228,
  BreathInspireAspiration = 13251046,
  BreathInspireBreathingLife = 15436141,
}

export enum BreathStringSizes {
  BreathNewPotentials = '9674897',
  BreathNewPotentialsUpdated = '17014',
  BreathReconditioning = '9503256',
  BreathChangingBeliefsAndPerceptions = '18036',
  BreathChangingBeliefsAndPerceptions2 = '11743',
  BreathInspireTribalTrance = '12921',
  BreathInspireEmergingHeart = '20626',
  BreathInspireSuenosSelva = '12733',
  BreathInspireInferno = '12909',
  BreathInspireRefuge = '18921',
  BreathInspireKingFisher = '17862',
  BreathInspireShamanGoddess = '11812',
  BreathInspireCleansing = '18238',
  BreathInspireAspiration = '13251',
  BreathInspireBreathingLife = '15436',
}

export const breathMap = {
  [BreathBaseKeys.BreathNewPotentials]: {
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    formattedDuration: '7',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathNewPotentials,
    name: 'Tuning Into New Potentials - Breath',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathNewPotentialsUpdated]: {
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    formattedDuration: '7',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathNewPotentialsUpdated,
    name: 'Tuning Into New Potentials - Breath - Updated',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathReconditioning]: {
    artist,
    backgroundImage: require('../assets/recondition.jpg'),
    formattedDuration: '8',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathReconditioning,
    name: 'Tuning Into New Potentials - Breath - Updated',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathChangingBeliefsAndPerceptions]: {
    artist,
    backgroundImage: require('../assets/changing-beliefs-and-perceptions.jpg'),
    formattedDuration: '12',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathChangingBeliefsAndPerceptions,
    name: 'Changing Beliefs and Perceptions - Breath',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireTribalTrance]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '5',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireTribalTrance,
    name: 'Inspire - Tribal Trance',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireEmergingHeart]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '8',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireEmergingHeart,
    name: 'Inspire - Emerging Heart',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireSuenosSelva]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '5',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireSuenosSelva,
    name: 'Inspire - Sueños de la Selva',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireInferno]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '5',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireInferno,
    name: 'Inspire - Inferno',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireRefuge]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '8',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireRefuge,
    name: 'Inspire - Refuge',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireKingFisher]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '7',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireKingFisher,
    name: 'Inspire - Kingfisher',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireShamanGoddess]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '5',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireShamanGoddess,
    name: 'Inspire - Shaman Goddess',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireCleansing]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '7',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireCleansing,
    name: 'Inspire - Cleansing',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [BreathBaseKeys.BreathInspireBreathingLife]: {
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    formattedDuration: '6',
    id: placeholder,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: BreathBaseKeys.BreathInspireBreathingLife,
    name: 'Inspire - Breathing Life',
    type: MeditationTypes.Breath,
    url: placeholder,
  },
};

/* Foundational */

export enum FoundationalBaseKeys {
  MedNewPotentials = 'm-new-potentials',
  MedNewPotentialsUpdated = 'm-new-potentials-updated',
  MedPresentMoment = 'm-present-moment',
  MedRecondition = 'm-recondition',
  MedChangingBeliefsAndPerceptions = 'm-changing-beliefs-and-perceptions',
  MedChangingBeliefsAndPerceptionsFull = 'm-changing-beliefs-and-perceptions-full',
}

export enum FoundationalSizes {
  MedNewPotentials = 56004113,
  MedNewPotentials2 = 46742444,
  MedNewPotentialsUpdated = 109548649,
  MedPresentMoment = 68710984,
  MedPresentMoment2 = 45584079,
  MedPresentMoment3 = 0,
  MedRecondition = 55295394,
  MedChangingBeliefsAndPerceptions = 64867301,
  MedChangingBeliefsAndPerceptions2 = 43092728,
  MedChangingBeliefsAndPerceptionsFull = 82233420,
}

export enum FoundationalStringSizes {
  MedNewPotentials = '96748',
  MedNewPotentials2 = '56004113',
  MedNewPotentialsUpdated = '17014',
  MedNewPotentialsUpdated2 = '10954',
  MedPresentMoment = '68710984',
  MedPresentMoment2 = '45584',
  MedPresentMoment3 = '45619',
  MedRecondition = '55295',
  MedChangingBeliefsAndPerceptions = '64867',
  MedChangingBeliefsAndPerceptions2 = '43092',
  MedChangingBeliefsAndPerceptionsFull = '82233',
}

export const foundationalMap = {
  [FoundationalBaseKeys.MedNewPotentials]: {
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    formattedDuration: '45',
    id: placeholder,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: FoundationalBaseKeys.MedNewPotentials,
    name: 'Tuning Into New Potentials',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [FoundationalBaseKeys.MedNewPotentialsUpdated]: {
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    formattedDuration: '45',
    id: placeholder,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: FoundationalBaseKeys.MedNewPotentialsUpdated,
    name: 'Tuning Into New Potentials - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [FoundationalBaseKeys.MedPresentMoment]: {
    artist,
    backgroundImage: require('../assets/present_moment.jpg'),
    formattedDuration: '47',
    id: placeholder,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: FoundationalBaseKeys.MedPresentMoment,
    name: 'Generous Present Moment',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [FoundationalBaseKeys.MedRecondition]: {
    artist,
    backgroundImage: require('../assets/recondition.jpg'),
    formattedDuration: '46',
    id: placeholder,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: FoundationalBaseKeys.MedRecondition,
    name: 'Reconditioning the Body to a New Mind',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [FoundationalBaseKeys.MedChangingBeliefsAndPerceptions]: {
    artist,
    backgroundImage: require('../assets/changing-beliefs-and-perceptions.jpg'),
    formattedDuration: '44',
    id: placeholder,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: FoundationalBaseKeys.MedChangingBeliefsAndPerceptions,
    name: 'Changing Beliefs and Perceptions - Meditation',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [FoundationalBaseKeys.MedChangingBeliefsAndPerceptionsFull]: {
    artist,
    backgroundImage: require('../assets/changing-beliefs-and-perceptions.jpg'),
    formattedDuration: '57',
    id: placeholder,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: FoundationalBaseKeys.MedChangingBeliefsAndPerceptionsFull,
    name: 'Changing Beliefs and Perceptions - Breath and Meditation',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Walking */

export enum WalkingBaseKeys {
  MedWalkingSteppingIntoYourFuture = 'm-walking-stepping-into-your-future',
  MedWalkingSteppingIntoYourFutureUpdated = 'm-walking-stepping-into-your-future-updated',
  MedWalkingWithTheDevine = 'm-walking-with-the-devine',
  MedWalkingWithTheDevineUpdated = 'm-walking-with-the-devine-updated',
  MedWalkingWithHeartFullMind = 'm-walking-with-heart-full-mind',
  MedWalkingBodyElectric = 'm-walking-body-electric',
  MedWalkingConditioningBody = 'm-walking-conditioning-body',
  MedWalkingNobleWalk = 'm-walking-noble-walk',
  MedWalkingUnlockingCode = 'm-walking-unlocking-code',
  MedWalkingPrayerEvocationInvocation = 'm-walking-prayer-evocation-invocation',
  MedWalkingRadiantLight = 'm-walking-radiant-light',
  MedWalkingRunning = 'm-walking-running',
}

export enum WalkingSizes {
  MedWalkingSteppingIntoYourFuture = 109611413,
  MedWalkingSteppingIntoYourFuture2 = 193892269,
  MedWalkingSteppingIntoYourFutureUpdated = 182182565,
  MedWalkingWithTheDevine = 88295823,
  MedWalkingWithTheDevineUpdated = 146895008,
  MedWalkingWithHeartFullMind = 168748185,
  MedWalkingWithHeartFullMind2 = 0,
  MedWalkingBodyElectric = 168658799,
  MedWalkingConditioningBody = 55287264,
  MedWalkingNobleWalk = 64241002,
  MedWalkingUnlockingCode = 35271555,
  MedWalkingUnlockingCode2 = 70655890,
  MedWalkingUnlockingCode3 = 0,
  MedWalkingPrayerEvocationInvocation = 72485220,
  MedWalkingPrayerEvocationInvocation2 = 72817185,
  MedWalkingPrayerEvocationInvocation3 = 108458482,
  MedWalkingRadiantLight = 123753113,
  MedWalkingRunning = 241626156,
}

export enum WalkingStringSizes {
  MedWalkingSteppingIntoYourFuture = '10961',
  MedWalkingSteppingIntoYourFuture2 = '19389',
  MedWalkingSteppingIntoYourFutureUpdated = '18218',
  MedWalkingWithTheDevine = '88295',
  MedWalkingWithTheDevineUpdated = '14689',
  MedWalkingWithHeartFullMind = '16874',
  MedWalkingWithHeartFullMind2 = '14102',
  MedWalkingBodyElectric = '16865',
  MedWalkingConditioningBody = '55287',
  MedWalkingNobleWalk = '64241',
  MedWalkingUnlockingCode = '35271',
  MedWalkingUnlockingCode2 = '70655',
  MedWalkingUnlockingCode3 = '87701',
  MedWalkingPrayerEvocationInvocation = '72485',
  MedWalkingPrayerEvocationInvocation2 = '72817',
  MedWalkingPrayerEvocationInvocation3 = '10845',
  MedWalkingPrayerEvocationInvocation4 = '10985',
  MedWalkingPrayerEvocationInvocation5 = '18080',
  MedWalkingRadiantLight = '12375',
  MedWalkingRunning = '24162',
}

export const walkingMap = {
  [WalkingBaseKeys.MedWalkingSteppingIntoYourFuture]: {
    artist,
    backgroundImage: require('../assets/wm-1.jpg'),
    formattedDuration: '76',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingSteppingIntoYourFuture,
    name: 'Walking Meditation 01 - Stepping into Your Future',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingSteppingIntoYourFutureUpdated]: {
    artist,
    backgroundImage: require('../assets/wm-1.jpg'),
    formattedDuration: '76',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingSteppingIntoYourFutureUpdated,
    name: 'Walking Meditation 01 - Stepping Into Your Future - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingWithTheDevine]: {
    artist,
    backgroundImage: require('../assets/wm-2.jpg'),
    formattedDuration: '61',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingWithTheDevine,
    name: 'Walking Meditation 02 - Walking with the Divine',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingWithTheDevineUpdated]: {
    artist,
    backgroundImage: require('../assets/wm-2.jpg'),
    formattedDuration: '61',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingWithTheDevineUpdated,
    name: 'Walking Meditation 02 - Walking with the Divine - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingWithHeartFullMind]: {
    artist,
    backgroundImage: require('../assets/wm-generic.jpg'),
    formattedDuration: '61',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingWithHeartFullMind,
    name: 'Walking Meditation 02 - Walking with the Divine - Updated',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingBodyElectric]: {
    artist,
    backgroundImage: require('../assets/wm-generic.jpg'),
    formattedDuration: '77',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingBodyElectric,
    name: 'Walking Meditation 11 - Body Electric',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingConditioningBody]: {
    artist,
    backgroundImage: require('../assets/wm-condition-body.jpg'),
    formattedDuration: '77',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingConditioningBody,
    name: 'Walking Meditation 04 - Conditioning the Body to a New Mind',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingNobleWalk]: {
    artist,
    backgroundImage: require('../assets/wm-condition-body.jpg'),
    formattedDuration: '67',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingNobleWalk,
    name: 'Walking Meditation 09 - The Noble Walk',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingUnlockingCode]: {
    artist,
    backgroundImage: require('../assets/wm-unlocking-code.jpg'),
    formattedDuration: '73',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingUnlockingCode,
    name: 'Walking Meditation 05 - Unlocking the Code',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingPrayerEvocationInvocation]: {
    artist,
    backgroundImage: require('../assets/wm-prayer-evo-invo.jpg'),
    formattedDuration: '75',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingPrayerEvocationInvocation,
    name: 'Walking Meditation 06 - Prayer of Evocation & Invocation',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingRadiantLight]: {
    artist,
    backgroundImage: require('../assets/wm-generic.jpg'),
    formattedDuration: '68',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingRadiantLight,
    name: 'Walking Meditation 12 - Walking In Radiant Light',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingBaseKeys.MedWalkingRunning]: {
    artist,
    backgroundImage: require('../assets/wm-generic.jpg'),
    formattedDuration: '45',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: WalkingBaseKeys.MedWalkingRunning,
    name: 'Walking Meditation - Running',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Syncronize */

export enum SynchronizeBaseKeys {
  MedSyncHealth = 'm-sync-health',
  MedSyncAbundance = 'm-sync-abundance',
  MedSyncEnergyToNewLife = 'm-sync-energy-to-new-life',
  MedSyncEnergyToLove = 'm-sync-energy-to-love',
}

export enum SynchronizeSizes {
  MedSyncHealth = 71508532,
  MedSyncHealth2 = 65433684,
  MedSyncAbundance = 98396012,
  MedSyncAbundance2 = 99503017,
  MedSyncAbundance3 = 66027719,
  MedSyncEnergyToNewLife = 75116576,
  MedSyncEnergyToNewLife2 = 79596550,
  MedSyncEnergyToLove = 104750945,
  MedSyncEnergyToLove2 = 96788471,
  MedSyncEnergyToLove3 = 69555367,
  MedSyncEnergyToLove4 = 13261422,
}

export enum SynchronizeStringSizes {
  MedSyncHealth = '71508',
  MedSyncHealth2 = '65433',
  MedSyncAbundance = '98396',
  MedSyncAbundance2 = '99503',
  MedSyncAbundance3 = '66027',
  MedSyncEnergyToNewLife = '75116',
  MedSyncEnergyToNewLife2 = '79596',
  MedSyncEnergyToLove = '10475',
  MedSyncEnergyToLove2 = '96788',
  MedSyncEnergyToLove3 = '69555',
  MedSyncEnergyToLove4 = '13261',
}

export const synchronizeMap = {
  [SynchronizeBaseKeys.MedSyncHealth]: {
    artist,
    backgroundImage: require('../assets/sync-energy-to-health.jpg'),
    formattedDuration: '79',
    id: placeholder,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: SynchronizeBaseKeys.MedSyncHealth,
    name: 'Synchronizing Your Energy To Health',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [SynchronizeBaseKeys.MedSyncEnergyToNewLife]: {
    artist,
    backgroundImage: require('../assets/sync-new-life.jpg'),
    formattedDuration: '85',
    id: placeholder,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: SynchronizeBaseKeys.MedSyncEnergyToNewLife,
    name: 'Synchronizing Your Energy To New Life',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [SynchronizeBaseKeys.MedSyncAbundance]: {
    artist,
    backgroundImage: require('../assets/sync-to-abundance.jpg'),
    formattedDuration: '74',
    id: placeholder,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: SynchronizeBaseKeys.MedSyncAbundance,
    name: 'Synchronizing Your Energy To Abundance',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [SynchronizeBaseKeys.MedSyncEnergyToLove]: {
    artist,
    backgroundImage: require('../assets/sync-energy-to-love.jpg'),
    formattedDuration: '82',
    id: placeholder,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: SynchronizeBaseKeys.MedSyncEnergyToLove,
    name: 'Synchronizing Your Energy To Love',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Unlocked */

export enum UnlockedBaseKeys {
  MedUnlockedS1P3 = 'm-unlocked-s1-p3',
  MedUnlockedS2P3 = 'm-unlocked-s2-p3',
  MedUnlockedS3P3 = 'm-unlocked-s3-p3',
  MedUnlockedS4P3 = 'm-unlocked-s4-p3',
}

export enum UnlockedSizes {
  MedUnlockedS1P3 = 82333740,
  MedUnlockedS2P3 = 106831373,
  MedUnlockedS3P3 = 121464787,
  MedUnlockedS4P3 = 107361827,
}

export enum UnlockedStringSizes {
  MedUnlockedS1P3 = '82333',
  MedUnlockedS2P3 = '10683',
  MedUnlockedS3P3 = '12146',
  MedUnlockedS4P3 = '10736',
}

export const unlockedMap = {
  [UnlockedBaseKeys.MedUnlockedS1P3]: {
    artist,
    backgroundImage: require('../assets/unlocked.jpg'),
    formattedDuration: '',
    id: placeholder,
    groupName: MeditationGroupName.Unlocked,
    meditationBaseId: UnlockedBaseKeys.MedUnlockedS1P3,
    name: 'Unlocked - Session 1 - Part 3',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [UnlockedBaseKeys.MedUnlockedS2P3]: {
    artist,
    backgroundImage: require('../assets/unlocked.jpg'),
    formattedDuration: '',
    id: placeholder,
    groupName: MeditationGroupName.Unlocked,
    meditationBaseId: UnlockedBaseKeys.MedUnlockedS2P3,
    name: 'Unlocked- Session 2 - Part 3',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [UnlockedBaseKeys.MedUnlockedS3P3]: {
    artist,
    backgroundImage: require('../assets/unlocked.jpg'),
    formattedDuration: '',
    id: placeholder,
    groupName: MeditationGroupName.Unlocked,
    meditationBaseId: UnlockedBaseKeys.MedUnlockedS3P3,
    name: 'Unlocked - Session 3 - Part 3',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [UnlockedBaseKeys.MedUnlockedS4P3]: {
    artist,
    backgroundImage: require('../assets/unlocked.jpg'),
    formattedDuration: '',
    id: placeholder,
    groupName: MeditationGroupName.Unlocked,
    meditationBaseId: UnlockedBaseKeys.MedUnlockedS4P3,
    name: 'Unlocked - Session 4 - Part 3',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Other */

export enum OtherBaseKeys {
  MedAlchemist = 'm-alchemist',
  MedChangingBoxes = 'm-changing-boxes',
  MedChangingBoxesSv = 'm-changing-boxes-sv',
  MedGoLove = 'm-go-love',
  MedHigherLoveCouples = 'm-higher-love-couples',
  MedLoveLifeYouLove = 'm-love-life-you-love',
  MedTurningYourLoveInward = 'm-turning-your-love-inward',
  MedHeartBrainSync = 'm-heart-brain-sync',
  MedCourageousHeart = 'm-courageous-heart',
  MedBreakingHabitsAddictions = 'm-breaking-habits-addictions',
  MedEmpoweringWithin = 'm-empowering-within',
  MedPinealGlandLong = 'm-pineal-gland-long',
  MedPinealGlandShort = 'm-pineal-gland-short',
  MedFallingIntoLoveBody = 'm-falling-into-love-body',
  MedTuneInWithYourHeart = 'm-tune-in-with-your-heart',
  MedCenterOfTheMagnet = 'm-center-of-the-magnet',
}

export enum OtherSizes {
  MedAlchemist = 146990579,
  MedAlchemist2 = 59139319,
  MedChangingBoxes = 75996112,
  MedChangingBoxes2 = 85420892,
  MedChangingBoxes3 = 50937439,
  MedGoLove = 12546994,
  MedGoLove2 = 30196275,
  MedGoLove3 = 22640150,
  MedHigherLoveCouples = 78649067,
  MedLoveLifeYouLove = 74235672,
  MedLoveLifeYouLove2 = 29873657,
  MedTurningYourLoveInward = 30255341,
  MedTurningYourLoveInward2 = 19411984,
  MedHeartBrainSync = 81972165,
  MedHeartBrainSync2 = 32977827,
  MedCourageousHeart = 89041318,
  MedBreakingHabitsAddictions = 86646730,
  MedEmpoweringWithin = 56628287,
  MedEmpoweringWithin2 = 59375853,
  MedPinealGlandLong = 121294523,
  MedPinealGlandShort = 61080546,
  MedPinealGlandShort2 = 80798855,
  MedFallingIntoLoveBody = 24779555,
  MedFallingIntoLoveBody2 = 62889102,
  MedFallingIntoLoveBody3 = 37064190,
  MedTuneInWithYourHeart = 73866145,
  MedCenterOfTheMagnet = 155540678,
}

export enum OtherStringSizes {
  MedAlchemist = '14699',
  MedAlchemist2 = '59139',
  MedChangingBoxes = '75996',
  MedChangingBoxes2 = '85420',
  MedChangingBoxes3 = '50937',
  MedChangingBoxesSv = '51829',
  MedGoLove = '12546',
  MedGoLove2 = '30196',
  MedGoLove3 = '22640',
  MedHigherLoveCouples = '78649',
  MedLoveLifeYouLove = '74235',
  MedLoveLifeYouLove2 = '29873',
  MedTurningYourLoveInward = '30255',
  MedTurningYourLoveInward2 = '19411',
  MedHeartBrainSync = '81972',
  MedHeartBrainSync2 = '32977',
  MedCourageousHeart = '89041',
  MedBreakingHabitsAddictions = '86646',
  MedEmpoweringWithin = '56628',
  MedEmpoweringWithin2 = '59375',
  MedPinealGlandLong = '12129',
  MedPinealGlandShort = '61080',
  MedPinealGlandShort2 = '80798',
  MedFallingIntoLoveBody = '24779',
  MedFallingIntoLoveBody2 = '62889',
  MedFallingIntoLoveBody3 = '37064',
  MedTuneInWIthYourHeart = '73866',
  MedCenterOfTheMagnet = '15554',
}

export const otherMap = {
  [OtherBaseKeys.MedAlchemist]: {
    artist,
    backgroundImage: require('../assets/alchemist.jpg'),
    formattedDuration: '61',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedAlchemist,
    name: 'The Alchemist',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedChangingBoxes]: {
    artist,
    backgroundImage: require('../assets/changing-boxes.jpg'),
    formattedDuration: '63',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedChangingBoxes,
    name: 'Changing Boxes',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedChangingBoxesSv]: {
    artist,
    backgroundImage: require('../assets/changing-boxes-short-version.jpg'),
    formattedDuration: '21',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedChangingBoxesSv,
    name: 'Changing Boxes - Short Version',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedGoLove]: {
    artist,
    backgroundImage: require('../assets/go-love.jpg'),
    formattedDuration: '16',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedGoLove,
    name: 'Go Love 20',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedHigherLoveCouples]: {
    artist,
    backgroundImage: require('../assets/higher-love-couples.jpg'),
    formattedDuration: '33',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedHigherLoveCouples,
    name: 'Higher Love for Couples',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedLoveLifeYouLove]: {
    artist,
    backgroundImage: require('../assets/lovelifeyoulove.jpg'),
    formattedDuration: '31',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedLoveLifeYouLove,
    name: 'Love The Life You Love',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedTurningYourLoveInward]: {
    artist,
    backgroundImage: require('../assets/turning-love-inward.jpg'),
    color: '#003E54',
    formattedDuration: '20',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedTurningYourLoveInward,
    name: 'Turning Your Love Inward',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedHeartBrainSync]: {
    artist,
    backgroundImage: require('../assets/heart-brain.jpg'),
    formattedDuration: '34',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedHeartBrainSync,
    name: 'Heart and Brain Sync',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedCourageousHeart]: {
    artist,
    backgroundImage: require('../assets/courageous-heart.jpg'),
    formattedDuration: '37',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedCourageousHeart,
    name: 'Courageous Heart',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedBreakingHabitsAddictions]: {
    artist,
    backgroundImage: require('../assets/habits-addictions.jpg'),
    formattedDuration: '60',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedBreakingHabitsAddictions,
    name: 'Breaking Habits and Addictions',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedEmpoweringWithin]: {
    artist,
    backgroundImage: require('../assets/empower-within.jpg'),
    formattedDuration: '39',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedEmpoweringWithin,
    name: 'Empowering the Power Within',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedPinealGlandLong]: {
    artist,
    backgroundImage: require('../assets/pineal-gland.jpg'),
    formattedDuration: '83',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedPinealGlandLong,
    name: 'Pineal Gland - Long',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedPinealGlandShort]: {
    artist,
    backgroundImage: require('../assets/pineal-gland.jpg'),
    formattedDuration: '64',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedPinealGlandShort,
    name: 'Pineal Gland - Short',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedFallingIntoLoveBody]: {
    artist,
    backgroundImage: require('../assets/falling-into-love-body.jpg'),
    formattedDuration: '36',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedFallingIntoLoveBody,
    name: 'Falling into Love with Your Body',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedTuneInWithYourHeart]: {
    artist,
    backgroundImage: require('../assets/tune-in-with-your-heart.jpg'),
    formattedDuration: '30',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedTuneInWithYourHeart,
    name: 'Tuning In With Your Heart',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedCenterOfTheMagnet]: {
    artist,
    backgroundImage: require('../assets/center-of-the-magnet.jpg'),
    formattedDuration: '160',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedCenterOfTheMagnet,
    name: 'Center of the Magnet',
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

export const meditationBaseMap: MeditationBaseMap = {
  ...botecMap,
  ...breakingHabitMap,
  ...breathMap,
  ...dailyMeditationsMap,
  ...foundationalMap,
  ...generatingMap,
  ...otherMap,
  ...synchronizeMap,
  ...unlockedMap,
  ...walkingMap,
};
