import {MeditationBaseMap, MeditationTypes} from '../types';

export enum MeditationBaseKeys {
  MedNewPotentialsV1 = 'm-new-potentials-v1',
  MedNewPotentialsV2 = 'm-new-potentials-v2',
  BreathNewPotentialsV1 = 'b-new-potentials-v1',
  BreathNewPotentialsV2 = 'b-new-potentials-v2',
  MedBreakingHabitSpaceV1 = 'm-breaking-habit-space-v1',
  MedBreakingHabitWaterV1 = 'm-breaking-habit-water-v1',
  MedPresentMomentV1 = 'm-present-moment-v1',
  MedPresentMomentV2 = 'm-present-moment-v2',
  MedDailyMorningV1 = 'm-daily-morning-v1',
  MedDailyMorningV2 = 'm-daily-morning-v2',
  MedDailyMorningUv = 'm-daily-morning-uv',
  MedDailyEveningV1 = 'm-daily-evening-v1',
  MedDailyEveningV2 = 'm-daily-evening-v2',
  MedDailyEveningUv = 'm-daily-evening-uv',
  MedReconditionV1 = 'm-recondition-v1',
  BreathReconditionV1 = 'b-recondition-v1',
  MedBlessingCenter1V1 = 'm-blessing-center-1-v1',
  MedBlessingCenter2V1 = 'm-blessing-center-2-v1',
  MedBlessingCenter3V1 = 'm-blessing-center-3-v1',
  MedBlessingCenter4V1 = 'm-blessing-center-4-v1',
  MedBlessingCenter5V1 = 'm-blessing-center-5-v1',
  MedBlessingCenter6V1 = 'm-blessing-center-6-v1',
  MedBlessingCenter6V2 = 'm-blessing-center-6-v2',
  MedBlessingCenter7V1 = 'm-blessing-center-7-v1',
  MedBlessingCenter7V2 = 'm-blessing-center-7-v2',
  MedBlessingCenter8V1 = 'm-blessing-center-8-v1',
  MedBlessingCenter8V2 = 'm-blessing-center-8-v2',
  MedBlessingCenter9V1 = 'm-blessing-center-9-v1',
  MedBlessingCenter9V2 = 'm-blessing-center-9-v2',
  MedBlessingCenter9V3 = 'm-blessing-center-9-v3',
  MedBlessingCenter10V1 = 'm-blessing-center-10-v1',
  MedBlessingCenter10V2 = 'm-blessing-center-10-v2',
  MedLoveLifeYouLoveV1 = 'm-love-life-you-love-v1',
  MedWalkingBodyElectricV1 = 'm-walking-body-electric-v1',
  MedWalkingConditioningBodyV1 = 'm-walking-conditioning-body-v1',
  MedWalkingPrayerEvocationInvocationV1 = 'm-walking-prayer-evocation-invocation-v1',
  MedWalkingPrayerEvocationInvocationV2 = 'm-walking-prayer-evocation-invocation-v2',
  MedWalkingNobleWalkV1 = 'm-walking-noble-walk-v1',
  MedWalkingUnlockingCodeV1 = 'm-walking-unlocking-code-v1',
  MedWalkingUnlockingCodeV2 = 'm-walking-unlocking-code-v2',
  MedWalkingMeditation1V1 = 'm-walking-meditation-1-v1',
  MedWalkingMeditation1V2 = 'm-walking-meditation-1-v2',
  MedWalkingMeditation2V1 = 'm-walking-meditation-2-v1',
  MedWalkingMeditation2V2 = 'm-walking-meditation-2-v2',
  MedWalkingHeartFullMindV1 = 'm-walking-heart-full-mind-v1',
  MedTurningYourLoveInwardV1 = 'm-turing-love-inwards-v1',
  MedTurningYourLoveInwardV2 = 'm-turing-love-inwards-v2',
  MedChangingBeliefsAndPerceptionsV1 = 'm-changing-beliefs-perceptions-v1',
  MedChangingBeliefsAndPerceptionsV2 = 'm-changing-beliefs-perceptions-v2',
  MedChangingBeliefsAndPerceptionsFullV1 = 'm-changing-beliefs-perceptions-full-v1',
  BreathChangingBeliefsAndPerceptionsV1 = 'b-changing-beliefs-perceptions-v1',
  BreathChangingBeliefsAndPerceptionsV2 = 'b-changing-beliefs-perceptions-v2',
  MedAlchemistV1 = 'm-alchemist-v1',
  MedAlchemistV2 = 'm-alchemist-v2',
  MedHeartBrainSyncV1 = 'm-heart-brain-sync-v1',
  MedHeartBrainSyncV2 = 'm-heart-brain-sync-v2',
  MedCourageousHeartV1 = 'm-courageous-heart-v1',
  MedBreakingHabitsAddictionsV1 = 'm-breaking-habits-addictions-v1',
  MedEmpoweringWithinV1 = 'm-empowering-within-v1',
  MedPinealGlandLongV1 = 'm-pineal-gland-long-v1',
  MedPinealGlandShortV1 = 'm-pineal-gland-short-v1',
  MedPinealGlandShortV2 = 'm-pineal-gland-short-v2',
  MedGeneratingAbundanceV1 = 'm-generating-abundance-v1',
  MedGeneratingFlowV1 = 'm-generating-flow-v1',
  MedGeneratingGratitudeV1 = 'm-generating-gratitude-v1',
  MedGeneratingEmpowermentV1 = 'm-generating-empowerment-v1',
  MedGeneratingEmpowermentV2 = 'm-generating-empowerment-v2',
  MedGeneratingChangeV1 = 'm-generating-change-v1',
  MedGeneratingInspirationV1 = 'm-generating-inspiration-v1',
  MedGeneratingJoyV1 = 'm-generating-joy-v1',
  BreathInspireEmergingHeartV1 = 'b-inspire-emerging-heart-v1',
  BreathInspireSuenosSelvaV1 = 'b-inspire-suenos-selva-v1',
  BreathInspireInfernoV1 = 'b-inspire-inferno-v1',
  BreathInspireTribalTranceV1 = 'b-inspire-tribal-trance-v1',
  BreathInspireRefugeV1 = 'b-inspire-refuge-v1',
  BreathInspireBreathingLifeV1 = 'b-inspire-breathing-life-v1',
  BreathInspireKingfisherV1 = 'b-inspire-kingfisher-v1',
  BreathInspireShamanGoddessV1 = 'b-inspire-shaman-goddess-v1',
  BreathInspireCleansingV1 = 'b-inspire-cleansing-v1',
  BreathInspireAspirationV1 = 'b-inspire-aspiration-v1',
  MedSyncToAbundanceV1 = 'm-sync-to-abundance-v1',
  MedFallingIntoLoveBody = 'm-falling-into-love-body',
  MedSyncEnergyToHealth = 'm-sync-energy-to-health',
  MedSyncEnergyToLoveV1 = 'm-sync-energy-to-love-v1',
  MedSyncEnergyToLoveV2 = 'm-sync-energy-to-love-v2',
  MedSyncEnergyToLoveV3 = 'm-sync-energy-to-love-v3',
  MedSyncEnergyToAbundance = 'm-sync-energy-to-abundance',
  MedSyncEnergyToNewLife = 'm-sync-energy-to-new-life',
  MedPlaceboV1 = 'm-placebo',
}

export enum MeditationStringSizes {
  MedNewPotentialsV1 = '56004',
  MedNewPotentialsV2 = '10954',
  BreathNewPotentialsV1 = '96748',
  BreathNewPotentialsV2 = '17014',
  MedBreakingHabitSpaceV1 = '14936',
  MedBreakingHabitWaterV1 = '14071',
  MedPresentMomentV1 = '68710',
  MedPresentMomentV2 = '45584',
  MedPresentMomentV3 = '45619',
  MedDailyMorningV1 = '34907',
  MedDailyMorningV2 = '23187',
  MedDailyMorningUv = '57534',
  MedDailyEveningV1 = '34099',
  MedDailyEveningV2 = '22604',
  MedDailyEveningUv = '56234',
  MedRecondition = '55295',
  BreathRecondition = '95032',
  MedBlessingCenter1V1 = '61719',
  MedBlessingCenter2V1 = '69705',
  MedBlessingCenter3V1 = '77717',
  MedBlessingCenter4V1 = '93864',
  MedBlessingCenter5V1 = '10421',
  MedBlessingCenter6V1 = '11010',
  MedBlessingCenter6V2 = '73078',
  MedBlessingCenter7V1 = '10765',
  MedBlessingCenter7V2 = '72338',
  MedBlessingCenter8V1 = '13596',
  MedBlessingCenter8V2 = '91332',
  MedBlessingCenter8V3 = '13440',
  MedBlessingCenter9V1 = '21175',
  MedBlessingCenter9V2 = '14923',
  MedBlessingCenter9V3 = '85552',
  MedBlessingCenter10V1 = '13820',
  MedBlessingCenter10V2 = '55797',
  MedLoveLifeV1 = '74235',
  MedLoveLifeV2 = '29873',
  MedWalkingBodyElectricV1 = '16865',
  MedWalkingConditioningBodyV1 = '55287',
  MedWalkingConditioningBodyMp3 = '19382',
  MedWalkingConditioningBodyMp3V2 = '55568',
  MedWalkingPrayerEvocationInvocationV1 = '72485',
  MedWalkingPrayerEvocationInvocationV2 = '72817',
  MedWalkingPrayerEvocationInvocationMp4 = '10985',
  MedWalkingPrayerEvocationInvocationMp3 = '18080',
  MedWalkingNobleWalkV1 = '64241',
  MedWalkingUnlockingCodeV1 = '35271',
  MedWalkingUnlockingCodeV2 = '70655',
  MedWalkingUnlockingCodeMp3 = '87701',
  MedWalkingMeditation1V1 = '10961',
  MedWalkingMeditation1V2 = '19389',
  MedWalkingMeditation2V1 = '88295',
  MedWalkingMeditation2V2 = '14689',
  MedWalkingHeartFullMindV1 = '16874',
  MedWalkingHeartFullMindV2 = '14102',
  MedTurningYourLoveInwardV1 = '30255',
  MedTurningYourLoveInwardV2 = '19411',
  MedChangingBeliefsAndPerceptionsFullV1 = '82233',
  MedChangingBeliefsAndPerceptionsV1 = '64867',
  MedChangingBeliefsAndPerceptionsV2 = '43092',
  BreathChangingBeliefsAndPerceptionsV1 = '18036',
  BreathChangingBeliefsAndPerceptionsV2 = '11743',
  MedAlchemistV1 = '14699',
  MedAlchemistV2 = '59139',
  MedHeartBrainSyncV1 = '81972',
  MedHeartBrainSyncV2 = '32977',
  MedCourageousHeartV1 = '89041',
  MedBreakingHabitsAddictionsV1 = '86646',
  MedEmpoweringWithinV1 = '56628',
  MedPinealGlandLongV1 = '12129',
  MedPinealGlandShortV1 = '61080',
  MedPinealGlandShortV2 = '80798',
  MedGeneratingAbundanceV1 = '86671',
  MedGeneratingFlowV1 = '14599',
  MedGeneratingGratitudeV1 = '14594',
  MedGeneratingEmpowermentV1 = '14596',
  MedGeneratingEmpowermentV2 = '14578',
  MedGeneratingChangeV1 = '14599',
  MedGeneratingInspirationV1 = '15099',
  MedGeneratingJoyV1 = '14593',
  BreathInspireEmergingHeartV1 = '20626',
  BreathInspireSuenosSelvaV1 = '12733',
  BreathInspireInfernoV1 = '12909',
  BreathInspireTribalV1 = '12921',
  BreathInspireRefugeV1 = '18921',
  BreathInspireBreathingLifeV1 = '15436',
  BreathInspireCleansingV1 = '18238',
  BreathInspireKingfisherV1 = '17862',
  BreathInspireShamanGoddessV1 = '11812',
  BreathInspireAspirationV1 = '13251',
  MedSyncToAbundanceV1 = '99503',
  MedFallingIntoLoveBody = '24779',
  MedSyncEnergyToHealth = '71508',
  MedSyncEnergyToLoveV1 = '96788',
  MedSyncEnergyToLoveV2 = '69555',
  MedSyncEnergyToLoveV3 = '13261',
  MedSyncEnergyToAbundance = '66027',
  MedSyncEnergyToNewLife = '79596',
  MedPlaceboV1 = '58249',
}

export enum MeditationKeys {
  NewPotentials = '56004113',
  NewPotentialsBreath = '9674897',
  BreakingTheHabit = '149360649',
  BreakingTheHabitWater = '140710975',
  PresentMoment = '68710984',
  DailyMorning = '34907925',
  DailyEvening = '34099801',
  Recondition = '55295394',
  ReconditionBreath = '9503256',
  LoveLifeYouLoveV1 = '74235672',
}

export enum MeditationSizes {
  NewPotentialsV1 = 56004113,
  NewPotentialsV2 = 109548649,
  NewPotentialsBreathV1 = 9674897,
  NewPotentialsBreathV2 = 17014748,
  BreakingTheHabit = 149360649,
  BreakingTheHabitWater = 140710975,
  PresentMomentV1 = 68710984,
  PresentMomentV2 = 45584079,
  DailyMorningV1 = 34907925,
  DailyMorningV2 = 23187022,
  DailyMorningUv = 57534699,
  DailyEveningV1 = 34099801,
  DailyEveningV2 = 22604281,
  DailyEveningUv = 56234919,
  Recondition = 55295394,
  ReconditionBreath = 9503256,
  BlessingEnergyCenter1V1 = 61719924,
  BlessingEnergyCenter2V1 = 69705557,
  BlessingEnergyCenter3V1 = 77717479,
  BlessingEnergyCenter4V1 = 93864414,
  BlessingEnergyCenter5V1 = 104215154,
  BlessingEnergyCenter6V1 = 110108828,
  BlessingEnergyCenter6V2 = 73078110,
  BlessingEnergyCenter7V1 = 107656059,
  BlessingEnergyCenter7V2 = 72338676,
  BlessingEnergyCenter8V1 = 135964319,
  BlessingEnergyCenter8V2 = 91332341,
  BlessingEnergyCenter9V1 = 211753731,
  BlessingEnergyCenter9V2 = 149230439,
  BlessingEnergyCenter9V3 = 85552981,
  BlessingEnergyCenter10V1 = 138202744,
  BlessingEnergyCenter10V2 = 55797552,
  LoveLifeYouLoveV1 = 74235672,
  WalkingBodyElectricV1 = 168658799,
  WalkingConditioningBodyV1 = 55287264,
  WalkingPrayerEvocationInvocationV1 = 72485220,
  WalkingPrayerEvocationInvocationV2 = 72817185,
  WalkingNobleWalkV1 = 64241002,
  WalkingUnlockingCodeV1 = 35271555,
  WalkingUnlockingCodeV2 = 70655890,
  WalkingMeditation1V1 = 109611413,
  WalkingMeditation1V2 = 193892269,
  WalkingMeditation2V1 = 88295823,
  WalkingMeditation2V2 = 146895008,
  WalkingHeartFullMindV1 = 168748185,
  TurningLoveInwardV1 = 30255341,
  TurningLoveInwardV2 = 19411984,
  BeliefsAndPerceptionsFullV1 = 82233420,
  BeliefsAndPerceptionsV1 = 64867301,
  BeliefsAndPerceptionsV2 = 43092728,
  BeliefsAndPerceptionsBreathV1 = 18036880,
  BeliefsAndPerceptionsBreathV2 = 11743205,
  AlchemistV1 = 146990579,
  AlchemistV2 = 59139319,
  HeartBrainSyncV1 = 81972165,
  HeartBrainSyncV2 = 32977827,
  CourageousHeartV1 = 89041318,
  BreakingHabitsAddictionsV1 = 86646730,
  EmpowerWithinV1 = 56628287,
  PinealGlandLongV1 = 121294523,
  PinealGlandShortV1 = 61080546,
  PinealGlandShortV2 = 80798855,
  GeneratingAbundance = 86671093,
  GeneratingFlow = 14599092,
  GeneratingGratitude = 14594274,
  GeneratingEmpowermentV1 = 14596134,
  GeneratingEmpowermentV2 = 14578838,
  GeneratingChange = 14599015,
  GeneratingInspiration = 15099669,
  GeneratingJoy = 14593178,
  InspireEmergingHeartV1 = 20626928,
  InspireSuenosSelvaV1 = 12733215,
  InspireInfernoV1 = 12909654,
  InspireTribalV1 = 12921155,
  InspireRefugeV1 = 18921020,
  InspireLifeV1 = 15436141,
  InspireCleansingV1 = 18238228,
  InspireKingfisherV1 = 17862421,
  InspireShamanGoddessV1 = 11812429,
  InspireAspirationV1 = 13251046,
  SyncToAbundanceV1 = 99503017,
  FallingIntoLoveBody = 24779555,
  SyncEnergyToHealth = 71508532,
  SyncEnergyToLoveV1 = 96788471,
  SyncEnergyToLoveV2 = 69555367,
  SyncEnergyToLoveV3 = 13261422,
  SyncEnergyToAbundance = 66027719,
  SyncEnergyToNewLife = 79596550,
  PlaceboV1 = 58249006,
}

export enum MeditationGroupKey {
  'AdvancedMeditations' = 'advancedMeditations',
  'BlessingEnergyCenter' = 'blessingEnergyCenter',
  'BreakingHabit' = 'breakingHabit',
  'BreathTracks' = 'breathTracks',
  'ChangeBeliefsAndPerceptions' = 'changingBeliefsAndPerceptions',
  'Daily' = 'daily',
  'Foundational' = 'foundational',
  'Generating' = 'generating',
  'Recondition' = 'recondition',
  'TuningNewPotential' = 'tuningNewPotential',
  'Walking' = 'walking',
  'Other' = 'other',
}

export enum MeditationGroupName {
  'BlessingEnergyCenter' = 'Blessing of the Energy Centers',
  'BreakingHabit' = 'Breaking the Habit of Being Yourself',
  'Daily' = 'Daily Meditations',
  'Generating' = 'Generating Series',
  'BreathTracks' = 'Breathwork',
  'Foundational' = 'Foundational - Progressive',
  'Walking' = 'Walking',
  'Synchronize' = 'Synchronize Series',
  'Unlocked' = 'Unlocked Series',
  'Other' = 'Other',
}

const artist = 'Dr. Joe Dispenza';
const placeholder = '';

/* Daily Series */

export enum DailySeriesBaseKeys {
  MedMorningUpdated = 'm-morning-updated',
  MedEveningUpdated = 'm-evening-updated',
}

export enum DailySeriesSizes {
  MedMorningUpdated = 33578871,
  MedEveningUpdated = 29178857,
}

export enum DailySeriesStringSizes {
  MedMorningUpdated = '33578',
  MedEveningUpdated = '29178',
}

const dailySeriesMap = {
  [DailySeriesBaseKeys.MedMorningUpdated]: {
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: DailySeriesBaseKeys.MedMorningUpdated,
    name: 'Daily Morning - Updated',
    size: DailySeriesSizes.MedMorningUpdated,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [DailySeriesBaseKeys.MedEveningUpdated]: {
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: DailySeriesBaseKeys.MedEveningUpdated,
    name: 'Daily Evening - Updated',
    size: DailySeriesSizes.MedEveningUpdated,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Generating Series */

export enum GeneratingSeriesBaseKeys {
  MedGeneratingJoy = 'm-generating-joy-v1',
}

export enum GeneratingSeriesSizes {
  MedGeneratingJoy = 14593178,
  MedGeneratingJoy2 = 36212123,
}

export enum GeneratingSeriesStringSizes {
  MedGeneratingJoy = '14593',
  MedGeneratingJoy2 = '36212',
}

const generatingSeriesMap = {
  [GeneratingSeriesBaseKeys.MedGeneratingJoy]: {
    artist,
    backgroundImage: require('../assets/generate-joy.jpg'),
    formattedDuration: '15',
    id: placeholder,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: GeneratingSeriesBaseKeys.MedGeneratingJoy,
    name: 'Generating Joy',
    size: GeneratingSeriesSizes.MedGeneratingJoy,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Other */

export enum OtherBaseKeys {
  MedAlchemist = 'm-alchemist-v1',
  MedAlchemist2 = 'm-alchemist-v2',
  MedAlchemist3 = 'm-alchemist-v3',
  MedChangingBoxes = 'm-changing-boxes',
  MedGoLove = 'm-go-love',
}

export enum OtherSizes {
  MedAlchemist = 146990579,
  MedAlchemist2 = 59139319,
  MedAlchemist3 = 106944456,
  MedChangingBoxes = 75996112,
  MedGoLove = 12546994,
}

export enum OtherStringSizes {
  MedAlchemist = '14699',
  MedAlchemist2 = '59139',
  MedAlchemist3 = '10694',
  MedChangingBoxes = '75996',
  MedGoLove = '12546',
}

const otherMap = {
  [OtherBaseKeys.MedAlchemist]: {
    artist,
    backgroundImage: require('../assets/alchemist.jpg'),
    formattedDuration: '61',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedAlchemist,
    name: 'The Alchemist',
    size: OtherSizes.MedAlchemist,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedAlchemist2]: {
    artist,
    backgroundImage: require('../assets/alchemist.jpg'),
    formattedDuration: '61',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedAlchemist2,
    name: 'The Alchemist',
    size: OtherSizes.MedAlchemist2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedAlchemist3]: {
    artist,
    backgroundImage: require('../assets/alchemist.jpg'),
    formattedDuration: '61',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedAlchemist3,
    name: 'The Alchemist',
    size: OtherSizes.MedAlchemist3,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedChangingBoxes]: {
    artist,
    backgroundImage: require('../assets/changing-boxes.jpg'),
    formattedDuration: '63',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedChangingBoxes,
    name: 'Changing Boxes',
    size: OtherSizes.MedChangingBoxes,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [OtherBaseKeys.MedGoLove]: {
    artist,
    backgroundImage: require('../assets/go-love.jpg'),
    formattedDuration: '16',
    id: placeholder,
    groupName: MeditationGroupName.Other,
    meditationBaseId: OtherBaseKeys.MedGoLove,
    name: 'Go Love 20',
    size: OtherSizes.MedGoLove,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Unlocked Series */

export enum UnlockedSeriesBaseKeys {
  MedUnlockedS1P3 = 'm-unlocked-s1-p3',
  MedUnlockedS2P3 = 'm-unlocked-s2-p3',
  MedUnlockedS3P3 = 'm-unlocked-s3-p3',
  MedUnlockedS4P3 = 'm-unlocked-s4-p3',
}

export enum UnlockedSeriesSizes {
  MedUnlockedS1P3 = 82333740,
  MedUnlockedS2P3 = 106831373,
  MedUnlockedS3P3 = 121464787,
  MedUnlockedS4P3 = 107361827,
}

export enum UnlockedSeriesStringSizes {
  MedUnlockedS1P3 = '82333',
  MedUnlockedS2P3 = '10683',
  MedUnlockedS3P3 = '12146',
  MedUnlockedS4P3 = '10736',
}

const unlockedSeriesMap = {
  [UnlockedSeriesBaseKeys.MedUnlockedS1P3]: {
    artist,
    backgroundImage: require('../assets/unlocked.jpg'),
    formattedDuration: '',
    id: placeholder,
    groupName: MeditationGroupName.Unlocked,
    meditationBaseId: UnlockedSeriesBaseKeys.MedUnlockedS1P3,
    name: 'Session 1 - Part 3',
    size: UnlockedSeriesSizes.MedUnlockedS1P3,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [UnlockedSeriesBaseKeys.MedUnlockedS2P3]: {
    artist,
    backgroundImage: require('../assets/unlocked.jpg'),
    formattedDuration: '',
    id: placeholder,
    groupName: MeditationGroupName.Unlocked,
    meditationBaseId: UnlockedSeriesBaseKeys.MedUnlockedS2P3,
    name: 'Session 2 - Part 3',
    size: UnlockedSeriesSizes.MedUnlockedS2P3,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [UnlockedSeriesBaseKeys.MedUnlockedS3P3]: {
    artist,
    backgroundImage: require('../assets/unlocked.jpg'),
    formattedDuration: '',
    id: placeholder,
    groupName: MeditationGroupName.Unlocked,
    meditationBaseId: UnlockedSeriesBaseKeys.MedUnlockedS3P3,
    name: 'Session 3 - Part 3',
    size: UnlockedSeriesSizes.MedUnlockedS3P3,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [UnlockedSeriesBaseKeys.MedUnlockedS4P3]: {
    artist,
    backgroundImage: require('../assets/unlocked.jpg'),
    formattedDuration: '',
    id: placeholder,
    groupName: MeditationGroupName.Unlocked,
    meditationBaseId: UnlockedSeriesBaseKeys.MedUnlockedS4P3,
    name: 'Session 4 - Part 3',
    size: UnlockedSeriesSizes.MedUnlockedS4P3,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Walking Meditations */
export enum WalkingMeditationBaseKeys {
  MedWalkingPrayerEvocationInvocation = 'm-walking-prayer-evocation-invocation-v1',
  MedWalkingPrayerEvocationInvocation2 = 'm-walking-prayer-evocation-invocation-v2',
  MedWalkingPrayerEvocationInvocation3 = 'm-walking-prayer-evocation-invocation-v3',
}

export enum WalkingMeditationSizes {
  MedWalkingPrayerEvocationInvocation = 72485220,
  MedWalkingPrayerEvocationInvocation2 = 72817185,
  MedWalkingPrayerEvocationInvocation3 = 108458482,
}

export enum WalkingMeditationStringSizes {
  MedWalkingPrayerEvocationInvocation = '72485',
  MedWalkingPrayerEvocationInvocation2 = '72817',
  MedWalkingPrayerEvocationInvocation3 = '10845',
  MedWalkingPrayerEvocationInvocation4 = '10985',
  MedWalkingPrayerEvocationInvocation5 = '18080',
}

const walkingMeditationMap = {
  [WalkingMeditationBaseKeys.MedWalkingPrayerEvocationInvocation]: {
    artist,
    backgroundImage: require('../assets/wm-prayer-evo-invo.jpg'),
    formattedDuration: '75',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId:
      WalkingMeditationBaseKeys.MedWalkingPrayerEvocationInvocation,
    name: 'Walking Meditation 06 - Prayer of Evocation & Invocation',
    size: WalkingMeditationSizes.MedWalkingPrayerEvocationInvocation,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingMeditationBaseKeys.MedWalkingPrayerEvocationInvocation2]: {
    artist,
    backgroundImage: require('../assets/wm-prayer-evo-invo.jpg'),
    formattedDuration: '75',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId:
      WalkingMeditationBaseKeys.MedWalkingPrayerEvocationInvocation2,
    name: 'Walking Meditation 06 - Prayer of Evocation & Invocation',
    size: WalkingMeditationSizes.MedWalkingPrayerEvocationInvocation2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [WalkingMeditationBaseKeys.MedWalkingPrayerEvocationInvocation3]: {
    artist,
    backgroundImage: require('../assets/wm-prayer-evo-invo.jpg'),
    formattedDuration: '75',
    id: placeholder,
    groupName: MeditationGroupName.Walking,
    meditationBaseId:
      WalkingMeditationBaseKeys.MedWalkingPrayerEvocationInvocation3,
    name: 'Walking Meditation 06 - Prayer of Evocation & Invocation',
    size: WalkingMeditationSizes.MedWalkingPrayerEvocationInvocation3,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
};

/* Meditation Base Map */

export const meditationBaseMap: MeditationBaseMap = {
  ...dailySeriesMap,
  ...generatingSeriesMap,
  ...otherMap,
  ...unlockedSeriesMap,
  ...walkingMeditationMap,
  [MeditationBaseKeys.MedNewPotentialsV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    color: '#055304',
    formattedDuration: '45',
    id: placeholder,
    groupKey: MeditationGroupKey.Foundational,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: MeditationBaseKeys.MedNewPotentialsV1,
    name: 'Tuning Into New Potentials',
    size: MeditationSizes.NewPotentialsV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedNewPotentialsV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    color: '#055304',
    formattedDuration: '45',
    id: placeholder,
    groupKey: MeditationGroupKey.Foundational,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: MeditationBaseKeys.MedNewPotentialsV2,
    name: 'Tuning Into New Potentials - Updated',
    size: MeditationSizes.NewPotentialsV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathNewPotentialsV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    color: '#055304',
    formattedDuration: '7',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathNewPotentialsV1,
    name: 'Tuning Into New Potentials - Breath',
    size: MeditationSizes.NewPotentialsBreathV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathNewPotentialsV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/new_potential.jpg'),
    color: '#055304',
    formattedDuration: '7',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathNewPotentialsV2,
    name: 'Tuning Into New Potentials - Breath - Updated',
    size: MeditationSizes.NewPotentialsBreathV2,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBreakingHabitSpaceV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/breaking_habit.jpg'),
    color: '#003E54',
    formattedDuration: '74',
    id: placeholder,
    groupKey: MeditationGroupKey.BreakingHabit,
    groupName: MeditationGroupName.BreakingHabit,
    meditationBaseId: MeditationBaseKeys.MedBreakingHabitSpaceV1,
    name: 'Breaking The Habit Of Being Yourself',
    size: MeditationSizes.BreakingTheHabit,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBreakingHabitWaterV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/breaking_habit.jpg'),
    color: '#003E54',
    formattedDuration: '70',
    id: placeholder,
    groupKey: MeditationGroupKey.BreakingHabit,
    groupName: MeditationGroupName.BreakingHabit,
    meditationBaseId: MeditationBaseKeys.MedBreakingHabitWaterV1,
    name: 'Breaking The Habit Of Being Yourself - Water',
    size: MeditationSizes.BreakingTheHabitWater,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedPresentMomentV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/present_moment.jpg'),
    color: '#003E54',
    formattedDuration: '47',
    id: placeholder,
    groupKey: MeditationGroupKey.Foundational,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: MeditationBaseKeys.MedPresentMomentV1,
    name: 'Generous Present Moment',
    size: MeditationSizes.PresentMomentV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedPresentMomentV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/present_moment.jpg'),
    color: '#003E54',
    formattedDuration: '47',
    id: placeholder,
    groupKey: MeditationGroupKey.Foundational,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: MeditationBaseKeys.MedPresentMomentV2,
    name: 'Generous Present Moment',
    size: MeditationSizes.PresentMomentV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedReconditionV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/recondition.jpg'),
    color: '#003E54',
    formattedDuration: '46',
    id: placeholder,
    groupKey: MeditationGroupKey.Foundational,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: MeditationBaseKeys.MedReconditionV1,
    name: 'Reconditioning the Body to a New Mind',
    size: MeditationSizes.Recondition,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathReconditionV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/recondition.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathReconditionV1,
    name: 'Reconditioning the Body to a New Mind - Breath',
    size: MeditationSizes.ReconditionBreath,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter1V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-1.jpg'),
    color: '#003E54',
    formattedDuration: '42',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter1V1,
    name: 'Blessing of the Energy Centers 01',
    size: MeditationSizes.BlessingEnergyCenter1V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter2V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-2.jpg'),
    color: '#003E54',
    formattedDuration: '47',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter2V1,
    name: 'Blessing of the Energy Centers 02',
    size: MeditationSizes.BlessingEnergyCenter2V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter3V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-3.jpg'),
    color: '#003E54',
    formattedDuration: '54',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter3V1,
    name: 'Blessing of the Energy Centers 03',
    size: MeditationSizes.BlessingEnergyCenter3V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter4V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-4.jpg'),
    color: '#003E54',
    formattedDuration: '65',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter4V1,
    name: 'Blessing of the Energy Centers 04',
    size: MeditationSizes.BlessingEnergyCenter4V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter5V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-5.jpg'),
    color: '#003E54',
    formattedDuration: '71',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter5V1,
    name: 'Blessing of the Energy Centers 05',
    size: MeditationSizes.BlessingEnergyCenter5V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter6V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-6.jpg'),
    color: '#003E54',
    formattedDuration: '75',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter6V1,
    name: 'Blessing of the Energy Centers 06',
    size: MeditationSizes.BlessingEnergyCenter6V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter6V2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-6.jpg'),
    color: '#003E54',
    formattedDuration: '75',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter6V2,
    name: 'Blessing of the Energy Centers 06',
    size: MeditationSizes.BlessingEnergyCenter6V2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter7V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-7.jpg'),
    color: '#003E54',
    formattedDuration: '74',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter7V1,
    name: 'Blessing of the Energy Centers 07',
    size: MeditationSizes.BlessingEnergyCenter7V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter7V2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-7.jpg'),
    color: '#003E54',
    formattedDuration: '74',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter7V2,
    name: 'Blessing of the Energy Centers 07',
    size: MeditationSizes.BlessingEnergyCenter7V2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter8V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-8.jpg'),
    color: '#003E54',
    formattedDuration: '94',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter8V1,
    name: 'Blessing of the Energy Centers 08',
    size: MeditationSizes.BlessingEnergyCenter8V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter8V2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-8.jpg'),
    color: '#003E54',
    formattedDuration: '94',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter8V2,
    name: 'Blessing of the Energy Centers 08',
    size: MeditationSizes.BlessingEnergyCenter8V2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter9V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-9.jpg'),
    color: '#003E54',
    formattedDuration: '88',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter9V1,
    name: 'Blessing of the Energy Centers 09',
    size: MeditationSizes.BlessingEnergyCenter9V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter9V2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-9.jpg'),
    color: '#003E54',
    formattedDuration: '88',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter9V2,
    name: 'Blessing of the Energy Centers 09',
    size: MeditationSizes.BlessingEnergyCenter9V2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter9V3]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-9.jpg'),
    color: '#003E54',
    formattedDuration: '88',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter9V3,
    name: 'Blessing of the Energy Centers 09',
    size: MeditationSizes.BlessingEnergyCenter9V3,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter10V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-10.jpg'),
    color: '#003E54',
    formattedDuration: '62',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter10V1,
    name: 'Blessing of the Energy Centers 10',
    size: MeditationSizes.BlessingEnergyCenter10V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBlessingCenter10V2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/bec-10.jpg'),
    color: '#003E54',
    formattedDuration: '62',
    id: placeholder,
    groupKey: MeditationGroupKey.BlessingEnergyCenter,
    groupName: MeditationGroupName.BlessingEnergyCenter,
    meditationBaseId: MeditationBaseKeys.MedBlessingCenter10V2,
    name: 'Blessing of the Energy Centers 10',
    size: MeditationSizes.BlessingEnergyCenter10V2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedDailyMorningV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    color: '#003E54',
    formattedDuration: '24',
    id: placeholder,
    groupKey: MeditationGroupKey.Daily,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: MeditationBaseKeys.MedDailyMorningV1,
    name: 'Daily Morning Meditation',
    size: MeditationSizes.DailyMorningV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedDailyMorningV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    color: '#003E54',
    formattedDuration: '24',
    id: placeholder,
    groupKey: MeditationGroupKey.Daily,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: MeditationBaseKeys.MedDailyMorningV2,
    name: 'Daily Morning Meditation',
    size: MeditationSizes.DailyMorningV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedDailyMorningUv]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    color: '#003E54',
    formattedDuration: '24',
    id: placeholder,
    groupKey: MeditationGroupKey.Daily,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: MeditationBaseKeys.MedDailyMorningUv,
    name: 'Daily Morning Meditation - Updated',
    size: MeditationSizes.DailyMorningUv,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedDailyEveningV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    color: '#003E54',
    formattedDuration: '23',
    id: placeholder,
    groupKey: MeditationGroupKey.Daily,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: MeditationBaseKeys.MedDailyEveningV1,
    name: 'Daily Evening Meditation',
    size: MeditationSizes.DailyEveningV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedDailyEveningV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    color: '#003E54',
    formattedDuration: '23',
    id: placeholder,
    groupKey: MeditationGroupKey.Daily,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: MeditationBaseKeys.MedDailyEveningV2,
    name: 'Daily Evening Meditation',
    size: MeditationSizes.DailyEveningV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedDailyEveningUv]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/daily.jpg'),
    color: '#003E54',
    formattedDuration: '23',
    id: placeholder,
    groupKey: MeditationGroupKey.Daily,
    groupName: MeditationGroupName.Daily,
    meditationBaseId: MeditationBaseKeys.MedDailyEveningUv,
    name: 'Daily Evening Meditation - Updated',
    size: MeditationSizes.DailyEveningUv,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedLoveLifeYouLoveV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/lovelifeyoulove.jpg'),
    color: '#003E54',
    formattedDuration: '31',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedLoveLifeYouLoveV1,
    name: 'Love The Life You Love',
    size: MeditationSizes.LoveLifeYouLoveV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingMeditation1V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-1.jpg'),
    color: '#003E54',
    formattedDuration: '76',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingMeditation1V1,
    name: 'Walking Meditation 01 - Stepping into Your Future',
    size: MeditationSizes.WalkingMeditation1V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingMeditation1V2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-1.jpg'),
    color: '#003E54',
    formattedDuration: '76',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingMeditation1V2,
    name: 'Walking Meditation 01 - Stepping into Your Future - Updated',
    size: MeditationSizes.WalkingMeditation1V2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingMeditation2V1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-2.jpg'),
    color: '#003E54',
    formattedDuration: '61',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingMeditation2V1,
    name: 'Walking Meditation 02 - Walking with the Divine',
    size: MeditationSizes.WalkingMeditation2V1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingMeditation2V2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-2.jpg'),
    color: '#003E54',
    formattedDuration: '61',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingMeditation2V2,
    name: 'Walking Meditation 02 - Walking with the Divine - Updated',
    size: MeditationSizes.WalkingMeditation2V2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingHeartFullMindV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-generic.jpg'),
    color: '#003E54',
    formattedDuration: '61',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingHeartFullMindV1,
    name: 'Walking Meditation 10 - Heart Full Mind',
    size: MeditationSizes.WalkingHeartFullMindV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingBodyElectricV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-generic.jpg'),
    color: '#003E54',
    formattedDuration: '77',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingBodyElectricV1,
    name: 'Walking Meditation 11 - Body Electric',
    size: MeditationSizes.WalkingBodyElectricV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingConditioningBodyV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-condition-body.jpg'),
    color: '#003E54',
    formattedDuration: '77',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingConditioningBodyV1,
    name: 'Walking Meditation 04 - Conditioning the Body to a New Mind',
    size: MeditationSizes.WalkingConditioningBodyV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingNobleWalkV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-generic.jpg'),
    color: '#003E54',
    formattedDuration: '67',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingNobleWalkV1,
    name: 'Walking Meditation 09 - The Noble Walk',
    size: MeditationSizes.WalkingNobleWalkV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingPrayerEvocationInvocationV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-prayer-evo-invo.jpg'),
    color: '#003E54',
    formattedDuration: '75',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingPrayerEvocationInvocationV1,
    name: 'Walking Meditation 06 - Prayer of Evocation & Invocation',
    size: MeditationSizes.WalkingPrayerEvocationInvocationV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingPrayerEvocationInvocationV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-prayer-evo-invo.jpg'),
    color: '#003E54',
    formattedDuration: '75',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingPrayerEvocationInvocationV2,
    name: 'Walking Meditation 06 - Prayer of Evocation & Invocation',
    size: MeditationSizes.WalkingPrayerEvocationInvocationV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingUnlockingCodeV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-unlocking-code.jpg'),
    color: '#003E54',
    formattedDuration: '73',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingUnlockingCodeV1,
    name: 'Walking Meditation 05 - Unlocking the Code',
    size: MeditationSizes.WalkingUnlockingCodeV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedWalkingUnlockingCodeV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/wm-unlocking-code.jpg'),
    color: '#003E54',
    formattedDuration: '73',
    id: placeholder,
    groupKey: MeditationGroupKey.Walking,
    groupName: MeditationGroupName.Walking,
    meditationBaseId: MeditationBaseKeys.MedWalkingUnlockingCodeV2,
    name: 'Walking Meditation 05 - Unlocking the Code',
    size: MeditationSizes.WalkingUnlockingCodeV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedTurningYourLoveInwardV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/turning-love-inward.jpg'),
    color: '#003E54',
    formattedDuration: '20',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedTurningYourLoveInwardV1,
    name: 'Turning Your Love Inward',
    size: MeditationSizes.TurningLoveInwardV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedTurningYourLoveInwardV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/turning-love-inward.jpg'),
    color: '#003E54',
    formattedDuration: '20',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedTurningYourLoveInwardV2,
    name: 'Turning Your Love Inward',
    size: MeditationSizes.TurningLoveInwardV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedChangingBeliefsAndPerceptionsFullV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/changing-beliefs-and-perceptions.jpg'),
    color: '#003E54',
    formattedDuration: '57',
    id: placeholder,
    groupKey: MeditationGroupKey.Foundational,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: MeditationBaseKeys.MedChangingBeliefsAndPerceptionsFullV1,
    name: 'Changing Beliefs and Perceptions - Breath and Meditation',
    size: MeditationSizes.BeliefsAndPerceptionsFullV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedChangingBeliefsAndPerceptionsV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/changing-beliefs-and-perceptions.jpg'),
    color: '#003E54',
    formattedDuration: '44',
    id: placeholder,
    groupKey: MeditationGroupKey.Foundational,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: MeditationBaseKeys.MedChangingBeliefsAndPerceptionsV1,
    name: 'Changing Beliefs and Perceptions - Meditation',
    size: MeditationSizes.BeliefsAndPerceptionsV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedChangingBeliefsAndPerceptionsV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/changing-beliefs-and-perceptions.jpg'),
    color: '#003E54',
    formattedDuration: '44',
    id: placeholder,
    groupKey: MeditationGroupKey.Foundational,
    groupName: MeditationGroupName.Foundational,
    meditationBaseId: MeditationBaseKeys.MedChangingBeliefsAndPerceptionsV2,
    name: 'Changing Beliefs and Perceptions - Meditation',
    size: MeditationSizes.BeliefsAndPerceptionsV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathChangingBeliefsAndPerceptionsV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/changing-beliefs-and-perceptions.jpg'),
    color: '#003E54',
    formattedDuration: '12',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathChangingBeliefsAndPerceptionsV1,
    name: 'Changing Beliefs and Perceptions - Breath',
    size: MeditationSizes.BeliefsAndPerceptionsBreathV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathChangingBeliefsAndPerceptionsV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/changing-beliefs-and-perceptions.jpg'),
    color: '#003E54',
    formattedDuration: '12',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathChangingBeliefsAndPerceptionsV2,
    name: 'Changing Beliefs and Perceptions - Breath',
    size: MeditationSizes.BeliefsAndPerceptionsBreathV2,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.MedAlchemistV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/alchemist.jpg'),
    color: '#003E54',
    formattedDuration: '61',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedAlchemistV1,
    name: 'The Alchemist',
    size: MeditationSizes.AlchemistV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedAlchemistV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/alchemist.jpg'),
    color: '#003E54',
    formattedDuration: '61',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedAlchemistV2,
    name: 'The Alchemist',
    size: MeditationSizes.AlchemistV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedHeartBrainSyncV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/heart-brain.jpg'),
    color: '#003E54',
    formattedDuration: '34',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedHeartBrainSyncV1,
    name: 'Heart and Brain Sync',
    size: MeditationSizes.HeartBrainSyncV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedHeartBrainSyncV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/heart-brain.jpg'),
    color: '#003E54',
    formattedDuration: '34',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedHeartBrainSyncV2,
    name: 'Heart and Brain Sync',
    size: MeditationSizes.HeartBrainSyncV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedCourageousHeartV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/courageous-heart.jpg'),
    color: '#003E54',
    formattedDuration: '37',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedCourageousHeartV1,
    name: 'Courageous Heart',
    size: MeditationSizes.CourageousHeartV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedBreakingHabitsAddictionsV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/habits-addictions.jpg'),
    color: '#003E54',
    formattedDuration: '60',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedBreakingHabitsAddictionsV1,
    name: 'Breaking Habits and Addictions',
    size: MeditationSizes.BreakingHabitsAddictionsV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedEmpoweringWithinV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/empower-within.jpg'),
    color: '#003E54',
    formattedDuration: '39',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedEmpoweringWithinV1,
    name: 'Empowering the Power Within',
    size: MeditationSizes.EmpowerWithinV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedPinealGlandLongV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/pineal-gland.jpg'),
    color: '#003E54',
    formattedDuration: '83',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedPinealGlandLongV1,
    name: 'Pineal Gland - Long',
    size: MeditationSizes.PinealGlandLongV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedPinealGlandShortV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/pineal-gland.jpg'),
    color: '#003E54',
    formattedDuration: '64',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedPinealGlandShortV1,
    name: 'Pineal Gland - Short',
    size: MeditationSizes.PinealGlandShortV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedPinealGlandShortV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/pineal-gland.jpg'),
    color: '#003E54',
    formattedDuration: '64',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedPinealGlandShortV2,
    name: 'Pineal Gland - Short',
    size: MeditationSizes.PinealGlandShortV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedGeneratingAbundanceV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/abundance.jpg'),
    color: '#003E54',
    formattedDuration: '60',
    id: placeholder,
    groupKey: MeditationGroupKey.Generating,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: MeditationBaseKeys.MedGeneratingAbundanceV1,
    name: 'Generating Abundance',
    size: MeditationSizes.GeneratingAbundance,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedGeneratingFlowV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/flow.jpg'),
    color: '#003E54',
    formattedDuration: '15',
    id: placeholder,
    groupKey: MeditationGroupKey.Generating,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: MeditationBaseKeys.MedGeneratingFlowV1,
    name: 'Generating Flow',
    size: MeditationSizes.GeneratingFlow,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedGeneratingGratitudeV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/gratitude.jpg'),
    color: '#003E54',
    formattedDuration: '15',
    id: placeholder,
    groupKey: MeditationGroupKey.Generating,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: MeditationBaseKeys.MedGeneratingGratitudeV1,
    name: 'Generating Gratitude',
    size: MeditationSizes.GeneratingGratitude,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedGeneratingEmpowermentV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/empowerment.jpg'),
    color: '#003E54',
    formattedDuration: '15',
    id: placeholder,
    groupKey: MeditationGroupKey.Generating,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: MeditationBaseKeys.MedGeneratingEmpowermentV1,
    name: 'Generating Empowerment',
    size: MeditationSizes.GeneratingEmpowermentV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedGeneratingEmpowermentV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/empowerment.jpg'),
    color: '#003E54',
    formattedDuration: '15',
    id: placeholder,
    groupKey: MeditationGroupKey.Generating,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: MeditationBaseKeys.MedGeneratingEmpowermentV2,
    name: 'Generating Empowerment',
    size: MeditationSizes.GeneratingEmpowermentV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedGeneratingChangeV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/change.jpg'),
    color: '#003E54',
    formattedDuration: '15',
    id: placeholder,
    groupKey: MeditationGroupKey.Generating,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: MeditationBaseKeys.MedGeneratingChangeV1,
    name: 'Generating Change',
    size: MeditationSizes.GeneratingChange,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedGeneratingInspirationV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '15',
    id: placeholder,
    groupKey: MeditationGroupKey.Generating,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: MeditationBaseKeys.MedGeneratingInspirationV1,
    name: 'Generating Inspiration',
    size: MeditationSizes.GeneratingInspiration,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedGeneratingJoyV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/generate-joy.jpg'),
    color: '#003E54',
    formattedDuration: '15',
    id: placeholder,
    groupKey: MeditationGroupKey.Generating,
    groupName: MeditationGroupName.Generating,
    meditationBaseId: MeditationBaseKeys.MedGeneratingJoyV1,
    name: 'Generating Joy',
    size: MeditationSizes.GeneratingJoy,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedSyncToAbundanceV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/sync-to-abundance.jpg'),
    color: '#003E54',
    formattedDuration: '74',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedSyncToAbundanceV1,
    name: 'Synchronizing Your Energy To Abundance - Advanced',
    size: MeditationSizes.SyncToAbundanceV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedFallingIntoLoveBody]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/falling-into-love-body.jpg'),
    color: '#003E54',
    formattedDuration: '36',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Other,
    meditationBaseId: MeditationBaseKeys.MedFallingIntoLoveBody,
    name: 'Falling into Love with Your Body',
    size: MeditationSizes.FallingIntoLoveBody,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireTribalTranceV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspire-breath.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireTribalTranceV1,
    name: 'Inspire - Tribal Trance',
    size: MeditationSizes.InspireTribalV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.MedSyncEnergyToHealth]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/sync-energy-to-health.jpg'),
    color: '#003E54',
    formattedDuration: '79',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: MeditationBaseKeys.MedSyncEnergyToHealth,
    name: 'Synchronizing Your Energy To Health',
    size: MeditationSizes.SyncEnergyToHealth,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedSyncEnergyToLoveV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/sync-energy-to-love.jpg'),
    color: '#003E54',
    formattedDuration: '82',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: MeditationBaseKeys.MedSyncEnergyToLoveV1,
    name: 'Synchronizing Your Energy To Love',
    size: MeditationSizes.SyncEnergyToLoveV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedSyncEnergyToLoveV2]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/sync-energy-to-love.jpg'),
    color: '#003E54',
    formattedDuration: '82',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: MeditationBaseKeys.MedSyncEnergyToLoveV2,
    name: 'Synchronizing Your Energy To Love',
    size: MeditationSizes.SyncEnergyToLoveV2,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedSyncEnergyToLoveV3]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/sync-energy-to-love.jpg'),
    color: '#003E54',
    formattedDuration: '82',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: MeditationBaseKeys.MedSyncEnergyToLoveV3,
    name: 'Synchronizing Your Energy To Love',
    size: MeditationSizes.SyncEnergyToLoveV3,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedSyncEnergyToAbundance]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/sync-abundance.jpg'),
    color: '#003E54',
    formattedDuration: '74',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: MeditationBaseKeys.MedSyncEnergyToAbundance,
    name: 'Synchronizing Your Energy To Abundance',
    size: MeditationSizes.SyncEnergyToAbundance,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedSyncEnergyToNewLife]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/sync-new-life.jpg'),
    color: '#003E54',
    formattedDuration: '85',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.Synchronize,
    meditationBaseId: MeditationBaseKeys.MedSyncEnergyToNewLife,
    name: 'Synchronizing Your Energy To New Life',
    size: MeditationSizes.SyncEnergyToNewLife,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.MedPlaceboV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/placebo.jpg'),
    color: '#003E54',
    formattedDuration: '69',
    id: placeholder,
    groupKey: MeditationGroupKey.Other,
    groupName: MeditationGroupName.BreakingHabit,
    meditationBaseId: MeditationBaseKeys.MedPlaceboV1,
    name: 'You are the Placebo',
    size: MeditationSizes.PlaceboV1,
    type: MeditationTypes.Meditation,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireEmergingHeartV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireEmergingHeartV1,
    name: 'Inspire - Emerging Heart',
    size: MeditationSizes.InspireEmergingHeartV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireSuenosSelvaV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireSuenosSelvaV1,
    name: 'Inspire - Sueños de la Selva',
    size: MeditationSizes.InspireSuenosSelvaV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireInfernoV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireInfernoV1,
    name: 'Inspire - Inferno',
    size: MeditationSizes.InspireInfernoV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireRefugeV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireRefugeV1,
    name: 'Inspire - Refuge',
    size: MeditationSizes.InspireRefugeV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireKingfisherV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireKingfisherV1,
    name: 'Inspire - Kingfisher',
    size: MeditationSizes.InspireKingfisherV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireShamanGoddessV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireShamanGoddessV1,
    name: 'Inspire - Shaman Goddess',
    size: MeditationSizes.InspireShamanGoddessV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireCleansingV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireCleansingV1,
    name: 'Inspire - Cleansing',
    size: MeditationSizes.InspireCleansingV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireAspirationV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireAspirationV1,
    name: 'Inspire - Aspiration',
    size: MeditationSizes.InspireAspirationV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
  [MeditationBaseKeys.BreathInspireBreathingLifeV1]: {
    artwork: '',
    artist,
    backgroundImage: require('../assets/inspiration.jpg'),
    color: '#003E54',
    formattedDuration: '8',
    id: placeholder,
    groupKey: MeditationGroupKey.BreathTracks,
    groupName: MeditationGroupName.BreathTracks,
    meditationBaseId: MeditationBaseKeys.BreathInspireBreathingLifeV1,
    name: 'Inspire - Breathing Life',
    size: MeditationSizes.InspireLifeV1,
    type: MeditationTypes.Breath,
    url: placeholder,
  },
};

export const breathMeditationTypeBaseIds = [
  MeditationBaseKeys.BreathNewPotentialsV1,
  MeditationBaseKeys.BreathReconditionV1,
];
