/**
 * Maps image keys (stored in Firestore catalog) to bundled require() assets.
 * This is the single source of truth for resolving image keys to native assets.
 */
const registry: Record<string, any> = {
  'abundance': require('../assets/abundance.jpg'),
  'alchemist': require('../assets/alchemist.jpg'),
  'bec-1': require('../assets/bec-1.jpg'),
  'bec-2': require('../assets/bec-2.jpg'),
  'bec-3': require('../assets/bec-3.jpg'),
  'bec-4': require('../assets/bec-4.jpg'),
  'bec-5': require('../assets/bec-5.jpg'),
  'bec-6': require('../assets/bec-6.jpg'),
  'bec-7': require('../assets/bec-7.jpg'),
  'bec-8': require('../assets/bec-8.jpg'),
  'bec-9': require('../assets/bec-9.jpg'),
  'bec-10': require('../assets/bec-10.jpg'),
  'blessings-from-the-brain': require('../assets/blessings-from-the-brain.png'),
  'breaking_habit': require('../assets/breaking_habit.jpg'),
  'center-of-the-magnet': require('../assets/center-of-the-magnet.jpg'),
  'change': require('../assets/change.jpg'),
  'changing-beliefs-and-perceptions': require('../assets/changing-beliefs-and-perceptions.jpg'),
  'changing-boxes': require('../assets/changing-boxes.jpg'),
  'changing-boxes-short-mei-lan': require('../assets/changing-boxes-short-mei-lan.png'),
  'changing-boxes-short-version': require('../assets/changing-boxes-short-version.jpg'),
  'changing-boxes-walking': require('../assets/changing-boxes-walking.png'),
  'count-your-blessings': require('../assets/count-your-blessings.png'),
  'courageous-heart': require('../assets/courageous-heart.jpg'),
  'daily': require('../assets/daily.jpg'),
  'empower-within': require('../assets/empower-within.jpg'),
  'empowerment': require('../assets/empowerment.jpg'),
  'falling-into-love-body': require('../assets/falling-into-love-body.jpg'),
  'flow': require('../assets/flow.jpg'),
  'generate-joy': require('../assets/generate-joy.jpg'),
  'go-love': require('../assets/go-love.jpg'),
  'gratitude': require('../assets/gratitude.jpg'),
  'habits-addictions': require('../assets/habits-addictions.jpg'),
  'heart-brain': require('../assets/heart-brain.jpg'),
  'higher-love-couples': require('../assets/higher-love-couples.jpg'),
  'inspiration': require('../assets/inspiration.jpg'),
  'inspire-breath': require('../assets/inspire-breath.jpg'),
  'inspire-v2': require('../assets/inspire-v2.png'),
  'life-love-and-the-mystical': require('../assets/life-love-and-the-mystical.png'),
  'love-your-body': require('../assets/love-your-body.png'),
  'lovelifeyoulove': require('../assets/lovelifeyoulove.jpg'),
  'new_potential': require('../assets/new_potential.jpg'),
  'outpicturing': require('../assets/outpicturing.png'),
  'pineal-gland': require('../assets/pineal-gland.jpg'),
  'placebo': require('../assets/placebo.jpg'),
  'present_moment': require('../assets/present_moment.jpg'),
  'recondition': require('../assets/recondition.jpg'),
  'sync-energy-to-health': require('../assets/sync-energy-to-health.jpg'),
  'sync-energy-to-love': require('../assets/sync-energy-to-love.jpg'),
  'sync-new-life': require('../assets/sync-new-life.jpg'),
  'sync-to-abundance': require('../assets/sync-to-abundance.jpg'),
  'tune-in-with-your-heart': require('../assets/tune-in-with-your-heart.jpg'),
  'turning-love-inward': require('../assets/turning-love-inward.jpg'),
  'unlocked': require('../assets/unlocked.jpg'),
  'wholly-days': require('../assets/wholly-days.png'),
  'wm-1': require('../assets/wm-1.jpg'),
  'wm-2': require('../assets/wm-2.jpg'),
  'wm-condition-body': require('../assets/wm-condition-body.jpg'),
  'wm-generic': require('../assets/wm-generic.jpg'),
  'wm-prayer-evo-invo': require('../assets/wm-prayer-evo-invo.jpg'),
  'wm-unlocking-code': require('../assets/wm-unlocking-code.jpg'),
  'wm-walk-for-the-world': require('../assets/wm-walk-for-the-world.jpg'),
};

export const getBackgroundImage = (key?: string): any => {
  if (!key) return undefined;
  return registry[key] || undefined;
};
