/**
 * Static Fingerprint Database Loader
 * 
 * Loads pre-generated fingerprint database from bundled JSON file.
 * This replaces the characteristic-based mock system with real file-based fingerprints.
 */

import {MeditationFingerprint} from './meditationFingerprintStorage';

// Import the real fingerprint database (will be generated by development script)
let realFingerprintDatabase: {[key: string]: MeditationFingerprint} | null = null;

/**
 * Load real fingerprint database from bundled file
 * Falls back to building database if static file doesn't exist
 */
export const loadStaticFingerprintDatabase = async (): Promise<{[key: string]: MeditationFingerprint}> => {
  // Try to load from static file first
  if (!realFingerprintDatabase) {
    try {
      // Import the static database file
      const staticDatabase = require('../assets/realFingerprintDatabase.json');
      realFingerprintDatabase = staticDatabase;
      console.log(`📱 Loaded static fingerprint database: ${Object.keys(staticDatabase).length} meditations`);
    } catch (error) {
      console.warn('⚠️ Static fingerprint database not found, will use dynamic generation');
      console.warn('To create static database, run: node scripts/buildRealFingerprintDatabase.js <meditation-files-dir>');
      
      // Fall back to building database dynamically
      const {buildReferenceDatabase} = await import('../services/databaseBuilder');
      const result = await buildReferenceDatabase();
      
      if (!result.success) {
        throw new Error(`Failed to build fingerprint database: ${result.error}`);
      }
      
      // Load the dynamically built database
      const {loadMeditationFingerprints} = await import('./meditationFingerprintStorage');
      realFingerprintDatabase = await loadMeditationFingerprints();
      
      console.log(`🔧 Built dynamic fingerprint database: ${result.count} meditations`);
    }
  }
  
  return realFingerprintDatabase || {};
};

/**
 * Get database statistics
 */
export const getDatabaseStats = async (): Promise<{
  source: 'static' | 'dynamic' | 'none';
  count: number;
  version?: string;
  lastUpdated?: string;
}> => {
  try {
    const database = await loadStaticFingerprintDatabase();
    const entries = Object.values(database);
    
    if (entries.length === 0) {
      return { source: 'none', count: 0 };
    }
    
    // Check if this is a static (v2.0) or dynamic (v1.0) database
    const firstEntry = entries[0];
    const isStatic = firstEntry.version === '2.0';
    
    return {
      source: isStatic ? 'static' : 'dynamic',
      count: entries.length,
      version: firstEntry.version,
      lastUpdated: firstEntry.lastUpdated,
    };
  } catch (error) {
    return { source: 'none', count: 0 };
  }
};

/**
 * Check if static database exists
 */
export const hasStaticDatabase = (): boolean => {
  try {
    require('../assets/realFingerprintDatabase.json');
    return true;
  } catch {
    return false;
  }
};

/**
 * Force reload of database (for development/testing)
 */
export const reloadDatabase = async (): Promise<void> => {
  realFingerprintDatabase = null;
  await loadStaticFingerprintDatabase();
};